/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test1.luxcafe;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurva
 */
public final class BillForm extends JFrame {

    /**
     * Creates new form KOTForm
     */
    public BillForm() {
        initComponents();
//        jTabbedPane.remove(jPanel1);
        createPendingBillPanel();
        createCompletedBillPanel();
        setLocationRelativeTo(null);
    }

    public BillForm(POS frame) {
        parentFrame = frame;
        parentFrame.setEnabled(false);
        initComponents();
        pendingTabbedPane.remove(jPanel1);
        createPendingBillPanel();
        createCompletedBillPanel();
        setLocationRelativeTo(null);
    }

    public BillForm(MainForm frame) {
        mainForm = frame;
        mainForm.setEnabled(false);
        initComponents();
        pendingTabbedPane.remove(jPanel1);
        createPendingBillPanel();
        createCompletedBillPanel();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentTabbedPane = new javax.swing.JTabbedPane();
        pendingPanel = new javax.swing.JPanel();
        pendingTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable1 = new javax.swing.JTable();
        CancelButton1 = new javax.swing.JButton();
        waterLabel1 = new javax.swing.JLabel();
        waiterNameLabel1 = new javax.swing.JLabel();
        orderTypeLabel1 = new javax.swing.JLabel();
        orderTypeValueLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalValueLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        waterLabel2 = new javax.swing.JLabel();
        waiterNameLabel2 = new javax.swing.JLabel();
        completedPanel = new javax.swing.JPanel();
        completedTabbedPane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable2 = new javax.swing.JTable();
        waterLabel3 = new javax.swing.JLabel();
        billIdLabel3 = new javax.swing.JLabel();
        customerLabel5 = new javax.swing.JLabel();
        orderTypeLabel2 = new javax.swing.JLabel();
        totalLabel2 = new javax.swing.JLabel();
        discountLabel1 = new javax.swing.JLabel();
        receviedLabel8 = new javax.swing.JLabel();
        paymentTypeLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bill");
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 0));

        orderTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Name", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable1.setRowSelectionAllowed(false);
        orderTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(orderTable1);
        if (orderTable1.getColumnModel().getColumnCount() > 0) {
            orderTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            orderTable1.getColumnModel().getColumn(0).setMaxWidth(40);
            orderTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
            orderTable1.getColumnModel().getColumn(2).setMaxWidth(40);
            orderTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            orderTable1.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        CancelButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CancelButton1.setText("Check Out");

        waterLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waterLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waterLabel1.setText("Waiter:");

        waiterNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        orderTypeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderTypeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderTypeLabel1.setText("Type:");

        orderTypeValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Total:");

        totalValueLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Bill ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        waterLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waterLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waterLabel2.setText("Customer:");

        waiterNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalValueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(waterLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waterLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waiterNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waiterNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(orderTypeLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderTypeValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderTypeLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(waterLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addComponent(waiterNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(orderTypeValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waiterNameLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(waterLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CancelButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        pendingTabbedPane.addTab("BT1", jPanel1);

        javax.swing.GroupLayout pendingPanelLayout = new javax.swing.GroupLayout(pendingPanel);
        pendingPanel.setLayout(pendingPanelLayout);
        pendingPanelLayout.setHorizontalGroup(
            pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pendingTabbedPane))
        );
        pendingPanelLayout.setVerticalGroup(
            pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(pendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pendingPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pendingTabbedPane)
                    .addContainerGap()))
        );

        parentTabbedPane.addTab("Pending", pendingPanel);

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 0));

        orderTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Name", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable2.setRowSelectionAllowed(false);
        orderTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(orderTable2);
        if (orderTable2.getColumnModel().getColumnCount() > 0) {
            orderTable2.getColumnModel().getColumn(0).setPreferredWidth(40);
            orderTable2.getColumnModel().getColumn(0).setMaxWidth(40);
            orderTable2.getColumnModel().getColumn(2).setPreferredWidth(40);
            orderTable2.getColumnModel().getColumn(2).setMaxWidth(40);
            orderTable2.getColumnModel().getColumn(3).setPreferredWidth(80);
            orderTable2.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        waterLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waterLabel3.setText("Waiter : This is a test name");

        billIdLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        billIdLabel3.setText("Bill ID : 21");

        customerLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerLabel5.setText("Customer : This is a test name");

        orderTypeLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderTypeLabel2.setText("Order Type : Take Away");

        totalLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalLabel2.setForeground(new java.awt.Color(153, 0, 0));
        totalLabel2.setText("Total : 2000/-");

        discountLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discountLabel1.setForeground(new java.awt.Color(153, 0, 0));
        discountLabel1.setText("Discount : 500/-");

        receviedLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        receviedLabel8.setForeground(new java.awt.Color(153, 0, 0));
        receviedLabel8.setText("Recevied : 1500/-");

        paymentTypeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentTypeLabel1.setForeground(new java.awt.Color(153, 0, 0));
        paymentTypeLabel1.setText("Type: Credit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(totalLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(discountLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(receviedLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paymentTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waterLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderTypeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(billIdLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billIdLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waterLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderTypeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(discountLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receviedLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentTypeLabel1))
                .addContainerGap())
        );

        completedTabbedPane.addTab("Sample", jPanel4);

        javax.swing.GroupLayout completedPanelLayout = new javax.swing.GroupLayout(completedPanel);
        completedPanel.setLayout(completedPanelLayout);
        completedPanelLayout.setHorizontalGroup(
            completedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(completedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(completedPanelLayout.createSequentialGroup()
                    .addComponent(completedTabbedPane)
                    .addContainerGap()))
        );
        completedPanelLayout.setVerticalGroup(
            completedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(completedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(completedPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(completedTabbedPane)
                    .addContainerGap()))
        );

        parentTabbedPane.addTab("Completed", completedPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(parentTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parentTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (parentFrame != null) {
            parentFrame.toFront();
            parentFrame.setEnabled(true);
        } else if (mainForm != null) {
            mainForm.toFront();
            mainForm.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private JTable createTable() {
        JTable orderTable = new JTable();
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "S.No.", "Name", "Qty", "Price"
                }
        ) {
            Class[] types = new Class[]{
                Integer.class, String.class, Integer.class, Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            orderTable.getColumnModel().getColumn(0).setMaxWidth(40);
            orderTable.getColumnModel().getColumn(2).setPreferredWidth(40);
            orderTable.getColumnModel().getColumn(2).setMaxWidth(40);
            orderTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            orderTable.getColumnModel().getColumn(3).setMaxWidth(80);
        }
        orderTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        return orderTable;
    }

    private int[] getOrderIdFromDB() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select order_id  from payment where status='pending'", false);
        int[] id = null;
        try {
            int i = 0;
            connect.resultSet.last();
            id = new int[connect.resultSet.getRow()];

            connect.resultSet.beforeFirst();
            while (connect.resultSet.next()) {
                id[i] = connect.resultSet.getInt("order_id");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    private Object[] getBillFromDB() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select *  from payment where status='completed' and payment_date >= CURRENT_DATE", false);
        Object[] items = null;
        try {
            connect.resultSet.last();
            items = new Object[connect.resultSet.getRow()];
            connect.resultSet.beforeFirst();
            int i = 0;
            while (connect.resultSet.next()) {
                Map item = new HashMap();
                item.put("id", connect.resultSet.getInt("id"));
                item.put("order_id", connect.resultSet.getInt("order_id"));
                item.put("amount", connect.resultSet.getInt("amount"));
                item.put("payment_date", connect.resultSet.getDate("payment_date"));
                item.put("payment_type", connect.resultSet.getString("payment_type"));
                item.put("discount", connect.resultSet.getInt("discount"));
                item.put("customer_id", connect.resultSet.getInt("customer_id"));
                item.put("user_id", connect.resultSet.getInt("user_id"));
                item.put("recevied_amount", connect.resultSet.getInt("recevied_amount"));
                items[i] = item;
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return items;
    }

    private Object[][] getOrderDetailsFromDB(int orderId) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select m.name,od.quantity,od.price from menu m join "
                + "order_details od on m.id = od.menu_id and od.order_id = " + orderId, false);
        Object[][] items = null;
        try {
            int i = 0;
            connect.resultSet.last();
            items = new Object[connect.resultSet.getRow()][4];
            connect.resultSet.beforeFirst();
            while (connect.resultSet.next()) {
                items[i][0] = i + 1;
                items[i][1] = connect.resultSet.getString("name");
                items[i][2] = connect.resultSet.getInt("quantity");
                items[i][3] = connect.resultSet.getInt("price");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return items;
    }

    private String getTableNameFromDB(int orderId) {
        String tableName = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select name from `table` t join `order` o on o.table_id=t.id and o.id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                tableName = connect.resultSet.getString("name");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tableName;
    }

    private String getStaffNameFromDB(int orderId) {
        String staffName = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select s.first_name,s.last_name from staff s join `order` o on o.staff_id=s.id and o.id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                staffName = connect.resultSet.getString("first_name") + " " + connect.resultSet.getString("last_name");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return staffName;
    }

    private String getOrderTypeFromDB(int orderId) {
        String orderType = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select type from `order` where id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                orderType = connect.resultSet.getString("type");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return orderType;
    }

    private void createPendingBillPanel() {
        for (int id : getOrderIdFromDB()) {
            JPanel orderPanel = new JPanel();
            JTable orderTable = createTable();
            JScrollPane tableScrollPane = new JScrollPane();
            JLabel waiterLabel = new JLabel();
            JLabel waiterValueLabel = new JLabel();
            JLabel orderTypeLabel = new JLabel();
            JLabel orderTypeValueLabel = new JLabel();
            JLabel customerLabel = new JLabel();
            JLabel customerValueLabel = new JLabel();
            JLabel billIdLabel = new JLabel();
            JLabel billIdValueLabel = new JLabel();
            JLabel totalLabel = new JLabel();
            JLabel totalValueLabel = new JLabel();
            JButton checkOutButton = new JButton();

            int customerId = getCustomerIdFromDB(id);
            Object[][] items = getOrderDetailsFromDB(id);

            DefaultTableModel dtm = (DefaultTableModel) orderTable.getModel();
            int totalPrice = 0;
            for (Object[] item : items) {
                dtm.addRow(item);
                totalPrice += (int) item[3];
            }
            totalValueLabel.setText(String.valueOf(totalPrice));
            tableScrollPane.setViewportView(orderTable);

            checkOutButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            checkOutButton.setText("Check Out");
            checkOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    JButton btn = (JButton) evt.getSource();
                    if (btn.isEnabled()) {
                        CheckoutForm checkoutForm = new CheckoutForm(btn, totalValueLabel.getText(), Integer.parseInt(getBillIdFromDB(id)));
                        checkoutForm.setVisible(true);
                    }
                }
            });

            waiterLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            waiterLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            waiterLabel.setText("Waiter:");
            waiterLabel.setName("waiterLabel");

            waiterValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N            
            waiterValueLabel.setText(getStaffNameFromDB(id));
            waiterValueLabel.setName("waiterValueLabel");

            orderTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            orderTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            orderTypeLabel.setText("Type:");
            orderTypeLabel.setName("orderTypeLabel");

            orderTypeValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            orderTypeValueLabel.setText(getOrderTypeFromDB(id));
            orderTypeValueLabel.setName("orderTypeValueLabel");

            customerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            customerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            customerLabel.setText("Customer:");
            customerLabel.setName("customerLabel");

            customerValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            if (customerId == 0) {
                customerValueLabel.setText("Not selected");
            } else {
                customerValueLabel.setText(getCustomerNameFromDB(customerId));
            }

            customerValueLabel.setName("customerValueLabel");

            billIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            billIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            billIdLabel.setText("Order Id:");
            billIdLabel.setName("orderIdLabel");

            billIdValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            billIdValueLabel.setText(getBillIdFromDB(id));
            billIdValueLabel.setName("orderIdValueLabel");

            totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            totalLabel.setText("Total:");
            totalLabel.setName("totalLabel");

            totalValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N            
            totalValueLabel.setName("totalValueLabel");
            totalValueLabel.setText(String.valueOf(totalPrice));

            GroupLayout jPanelLayout = new GroupLayout(orderPanel);

            orderPanel.setLayout(jPanelLayout);
            jPanelLayout.setHorizontalGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                            .addComponent(checkOutButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(totalLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(totalValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                            .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                                            .addComponent(waiterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(waiterValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanelLayout.createSequentialGroup()
                                                            .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(customerValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(billIdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(orderTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(billIdValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(orderTypeValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                            .addContainerGap())
            );
            jPanelLayout.setVerticalGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(waiterValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(waiterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                    .addComponent(orderTypeLabel)
                                    .addComponent(orderTypeValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(customerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                    .addComponent(customerValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(billIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(billIdValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalLabel)
                                    .addComponent(totalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
            );
            pendingTabbedPane.addTab(getTableNameFromDB(id), orderPanel);
        }
    }

    public void createCompletedBillPanel() {
        completedTabbedPane.removeAll();
        for (Object object : getBillFromDB()) {
            Map map = (HashMap) object;
            JPanel orderPanel = new JPanel();
            JTable orderTable = createTable();
            JScrollPane tableScrollPane = new JScrollPane();
            JLabel waiterLabel = new JLabel();
            JLabel orderTypeLabel = new JLabel();
            JLabel customerLabel = new JLabel();
            JLabel billIdLabel = new JLabel();

            JLabel totalLabel = new JLabel();
            JLabel discountLabel = new JLabel();
            JLabel receviedLabel = new JLabel();
            JLabel paymentTypeLabel = new JLabel();

            int customerId = (int) map.get("customer_id");
            
            DefaultTableModel dtm = (DefaultTableModel) orderTable.getModel();
            
            for (Object[] item : getOrderDetailsFromDB((int) map.get("order_id"))) {
                dtm.addRow(item);                
            }

            tableScrollPane.setViewportView(orderTable);

            waiterLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            waiterLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            waiterLabel.setText("Waiter : " + getStaffNameFromDB((int) map.get("order_id")));

            orderTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            orderTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            orderTypeLabel.setText("Type : " + getOrderTypeFromDB((int) map.get("order_id")));

            customerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            customerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            customerLabel.setName("customerLabel");
            if (customerId == 0) {
                customerLabel.setText("Customer :");
            } else {
                customerLabel.setText("Customer : " + getCustomerNameFromDB(customerId));
            }

            billIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            billIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            billIdLabel.setText("Bill Id : " + map.get("id"));

            totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            totalLabel.setForeground(new java.awt.Color(153, 0, 0));
            totalLabel.setText("Total : " + map.get("amount"));

            discountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            discountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            discountLabel.setForeground(new java.awt.Color(153, 0, 0));
            discountLabel.setText("Discount : " + map.get("discount"));

            receviedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            receviedLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            receviedLabel.setForeground(new java.awt.Color(153, 0, 0));
            receviedLabel.setText("Received : " + map.get("recevied_amount"));

            paymentTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            paymentTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            paymentTypeLabel.setForeground(new java.awt.Color(153, 0, 0));
            paymentTypeLabel.setText("Type : " + map.get("payment_type"));

            GroupLayout jPanelLayout = new GroupLayout(orderPanel);

            orderPanel.setLayout(jPanelLayout);
            jPanelLayout.setHorizontalGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                                            .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(receviedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(paymentTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tableScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(waiterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(orderTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                    .addComponent(billIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanelLayout.setVerticalGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(waiterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(billIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(11, 11, 11)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orderTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                    .addComponent(discountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(receviedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentTypeLabel))
                            .addContainerGap())
            );

            completedTabbedPane.addTab(getTableNameFromDB((int)map.get("order_id")), orderPanel);
        }
    }

    private int getCustomerIdFromDB(int orderId) {
        int id = 0;
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select customer_id from `order` where id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                id = connect.resultSet.getInt("customer_id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    private String getCustomerNameFromDB(int id) {
        String name = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select first_name,last_name from `customer` where id=" + id, false);
        try {
            if (connect.resultSet.next()) {
                name = connect.resultSet.getString("first_name") + " " + connect.resultSet.getString("last_name");
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return name;
    }

    private String getBillIdFromDB(int orderId) {
        String billId = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select id from payment where order_id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                billId = String.valueOf(connect.resultSet.getInt("id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(BillForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return billId;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillForm().setVisible(true);
            }
        });
    }

    POS parentFrame;
    MainForm mainForm;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton1;
    private javax.swing.JLabel billIdLabel3;
    private javax.swing.JPanel completedPanel;
    private javax.swing.JTabbedPane completedTabbedPane;
    private javax.swing.JLabel customerLabel5;
    private javax.swing.JLabel discountLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable1;
    private javax.swing.JTable orderTable2;
    private javax.swing.JLabel orderTypeLabel1;
    private javax.swing.JLabel orderTypeLabel2;
    private javax.swing.JLabel orderTypeValueLabel1;
    private javax.swing.JTabbedPane parentTabbedPane;
    private javax.swing.JLabel paymentTypeLabel1;
    private javax.swing.JPanel pendingPanel;
    private javax.swing.JTabbedPane pendingTabbedPane;
    private javax.swing.JLabel receviedLabel8;
    private javax.swing.JLabel totalLabel2;
    private javax.swing.JLabel totalValueLabel1;
    private javax.swing.JLabel waiterNameLabel1;
    private javax.swing.JLabel waiterNameLabel2;
    private javax.swing.JLabel waterLabel1;
    private javax.swing.JLabel waterLabel2;
    private javax.swing.JLabel waterLabel3;
    // End of variables declaration//GEN-END:variables
}
