/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test1.luxcafe;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author apurva
 */
public class CheckoutForm extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutForm
     */
    public CheckoutForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public CheckoutForm(JButton btn, String total, int billId) {
        parentButton = btn;
        billForm = (BillForm) SwingUtilities.getWindowAncestor(btn);
        billForm.setEnabled(false);
        this.billId = billId;
        initComponents();
        billAmountTextField.setText(total);
        netAmountTextField.setText(total);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        billAmountTextField = new javax.swing.JTextField();
        discountTextField = new javax.swing.JTextField();
        netAmountTextField = new javax.swing.JTextField();
        percentToggleButton = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cashReceviedTextField = new javax.swing.JTextField();
        changeTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        paymentTypeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check Out");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setLabelFor(billAmountTextField);
        jLabel2.setText("Bill Amount");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setLabelFor(discountTextField);
        jLabel3.setText("Discount");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setLabelFor(netAmountTextField);
        jLabel4.setText("Net Amount");

        billAmountTextField.setEditable(false);
        billAmountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        billAmountTextField.setText("110");
        billAmountTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        billAmountTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        billAmountTextField.setEnabled(false);

        discountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                discountTextFieldFocusLost(evt);
            }
        });
        discountTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discountTextFieldKeyTyped(evt);
            }
        });

        netAmountTextField.setEditable(false);
        netAmountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        netAmountTextField.setText("110");
        netAmountTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        netAmountTextField.setEnabled(false);

        percentToggleButton.setText("%");
        percentToggleButton.setToolTipText("");
        percentToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                percentToggleButtonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setLabelFor(cashReceviedTextField);
        jLabel5.setText("Cash Received");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setLabelFor(changeTextField);
        jLabel6.setText("Change");

        cashReceviedTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashReceviedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cashReceviedTextFieldKeyTyped(evt);
            }
        });

        changeTextField.setEditable(false);
        changeTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        changeTextField.setEnabled(false);

        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setLabelFor(paymentTypeComboBox);
        jLabel7.setText("Payment Type");

        paymentTypeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "QR", "Credit" }));
        paymentTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paymentTypeComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billAmountTextField)
                            .addComponent(cashReceviedTextField))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(discountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(changeTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(percentToggleButton)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(paymentTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(netAmountTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(percentToggleButton)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cashReceviedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(changeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (billForm != null) {
            billForm.toFront();
            billForm.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        int discount = 0;
        if (!discountTextField.getText().equals("")) {
            discount = Integer.parseInt(discountTextField.getText());
            if (percentToggleButton.isSelected()) {
                int billAmount = Integer.parseInt(billAmountTextField.getText());
                int netAmount = Integer.parseInt(netAmountTextField.getText());
                discount = billAmount - netAmount;
            }
        }
        int netAmount = Integer.parseInt(netAmountTextField.getText());
        String paymentType = (String) paymentTypeComboBox.getSelectedItem();
        if (paymentType.equals("Credit")) {
            int cid = getCustomerIDFromDB(billId);
            if (cid == 0) {
                if (JOptionPane.showConfirmDialog(null, "Please select a customer for credit option", "Alert", JOptionPane.OK_CANCEL_OPTION) == 0) {
                    list = new Object[]{discount, netAmount, paymentType};
                    CustomerForm customerForm = new CustomerForm((CheckoutForm) SwingUtilities.getWindowAncestor(((JButton) evt.getSource()).getParent()));
                    customerForm.setVisible(true);
                }
            } else {
                updatePaymentTable(discount, netAmount, paymentType);
            }
        } else {
            updatePaymentTable(discount, netAmount, paymentType);
        }


    }//GEN-LAST:event_saveButtonMouseClicked

    private void discountTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discountTextFieldFocusLost
        int billAmount = Integer.parseInt(billAmountTextField.getText());
        String discountText = discountTextField.getText();
        if (!discountText.equals("")) {
            if (percentToggleButton.isSelected()) {
                int dis = (int) Math.round(Integer.parseInt(discountText) * billAmount * 0.01);
                netAmountTextField.setText(String.valueOf(billAmount - dis));
            } else {
                netAmountTextField.setText(String.valueOf(billAmount - Integer.parseInt(discountText)));
            }
            setChange();
        } else {
            netAmountTextField.setText(String.valueOf(billAmount));
            setChange();
        }
    }//GEN-LAST:event_discountTextFieldFocusLost


    private void discountTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (("" + c).matches("[0-9]")) {
            if (!"".equals(discountTextField.getText())) {
                int billAmount = Integer.parseInt(billAmountTextField.getText());
                int discount = Integer.parseInt(discountTextField.getText() + String.valueOf(c));
                if (billAmount <= discount * 2) {  // restrict discount to 50%
                    evt.consume();
                }
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_discountTextFieldKeyTyped

    private void percentToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentToggleButtonMouseClicked
        if (!discountTextField.getText().equals("")) {
            int billAmount = Integer.parseInt(billAmountTextField.getText());
            String discountText = discountTextField.getText();
            if (((JToggleButton) evt.getSource()).isSelected()) {
                int dis = (int) Math.round(Integer.parseInt(discountText) * billAmount * 0.01);
                netAmountTextField.setText(String.valueOf(billAmount - dis));
            } else {
                netAmountTextField.setText(String.valueOf(billAmount - Integer.parseInt(discountText)));
            }
            setChange();
        }
    }//GEN-LAST:event_percentToggleButtonMouseClicked

    private void cashReceviedTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cashReceviedTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (("" + c).matches("[0-9]")) {
            if (!"".equals(cashReceviedTextField.getText())) {
                int cashAmount = Integer.parseInt(cashReceviedTextField.getText() + c);
                int netAmount = Integer.parseInt(netAmountTextField.getText());
                if (cashAmount - netAmount >= 0) {
                    changeTextField.setText(String.valueOf(cashAmount - netAmount));
                }
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_cashReceviedTextFieldKeyTyped

    private void paymentTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paymentTypeComboBoxItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String item = evt.getItem().toString();
            switch (item) {
                case "Cash" -> {
                    cashReceviedTextField.setEnabled(true);
                    discountTextField.setEnabled(true);
                }
                case "QR" -> {
                    cashReceviedTextField.setText("");
                    cashReceviedTextField.setEnabled(false);
                    changeTextField.setText("");
                }
                case "Credit" -> {
                    cashReceviedTextField.setText("");
                    cashReceviedTextField.setEnabled(false);
                    discountTextField.setText("");
                    discountTextField.setEnabled(false);
                    netAmountTextField.setText(billAmountTextField.getText());
                    changeTextField.setText("");
                }

            }
        }

    }//GEN-LAST:event_paymentTypeComboBoxItemStateChanged

    private int getCustomerIDFromDB(int billId) {
        int customerId = 0;
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select customer_id from payment where id=" + billId, false);
        try {
            if (connect.resultSet.next()) {
                customerId = connect.resultSet.getInt("customer_id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CheckoutForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return customerId;
    }

    private void setChange() {
        String cashReceived = cashReceviedTextField.getText();
        int netAmount = Integer.parseInt(netAmountTextField.getText());
        if (!cashReceived.equals("")) {
            int cr = Integer.parseInt(cashReceived);
            if (cr - netAmount < 0) {
                cashReceviedTextField.setText("");
                changeTextField.setText("");
            } else {
                changeTextField.setText(String.valueOf(cr - netAmount));
            }
        }
    }

    private void updatePaymentTable(int discount, int netAmount, String paymentType) {
        DBConnect connect = new DBConnect();
        if (paymentType.equals("Credit") && customerId != 0) {
            connect.insertStatement("update payment set discount=" + discount + ",recevied_amount="
                    + netAmount + ",payment_type='" + paymentType + "',status='Completed',customer_id=" + customerId + " where id=" + billId, false);
        } else {
            connect.insertStatement("update payment set discount=" + discount + ",recevied_amount="
                    + netAmount + ",payment_type='" + paymentType + "',status='Completed' where id=" + billId, false);
        }
        if (parentButton != null) {
            parentButton.setEnabled(false);
            billForm.createCompletedBillPanel();
            billForm.toFront();
            billForm.setEnabled(true);
            dispose();
        }
    }

    public void updateCreditor() {
        updatePaymentTable((int) list[0], (int) list[1], (String) list[2]);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckoutForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckoutForm().setVisible(true);
            }
        });
    }

    BillForm billForm;
    JButton parentButton;
    int customerId = 0;
    Object[] list;
    int billId;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billAmountTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cashReceviedTextField;
    private javax.swing.JTextField changeTextField;
    private javax.swing.JTextField discountTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField netAmountTextField;
    private javax.swing.JComboBox<String> paymentTypeComboBox;
    private javax.swing.JToggleButton percentToggleButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
