/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test1.luxcafe;

import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurva
 */
public class KOTForm extends JFrame {

    /**
     * Creates new form KOTForm
     */
    public KOTForm() {
        initComponents();
//        jTabbedPane.remove(jPanel1);
        createOrderPanel();
        setLocationRelativeTo(null);
    }

    public KOTForm(POS frame) {
        parentFrame = frame;
        parentFrame.setEnabled(false);
        initComponents();
        jTabbedPane.remove(jPanel1);
        createOrderPanel();
        setLocationRelativeTo(null);
    }

    public KOTForm(MainForm frame) {
        mainForm = frame;
        mainForm.setEnabled(false);
        initComponents();
        jTabbedPane.remove(jPanel1);
        createOrderPanel();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable1 = new javax.swing.JTable();
        CompleteButton1 = new javax.swing.JButton();
        CancelButton1 = new javax.swing.JButton();
        updateButton1 = new javax.swing.JButton();
        waiterLabel1 = new javax.swing.JLabel();
        waiterValueLabel1 = new javax.swing.JLabel();
        orderTypeLabel1 = new javax.swing.JLabel();
        orderTypeValueLabel1 = new javax.swing.JLabel();
        totalLabel1 = new javax.swing.JLabel();
        totalValueLabel2 = new javax.swing.JLabel();
        customerLabel2 = new javax.swing.JLabel();
        customerValueLabel2 = new javax.swing.JLabel();
        orderIdLabel2 = new javax.swing.JLabel();
        orderIdValueLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Order");
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 0));

        orderTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Name", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable1.setRowSelectionAllowed(false);
        orderTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(orderTable1);
        if (orderTable1.getColumnModel().getColumnCount() > 0) {
            orderTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            orderTable1.getColumnModel().getColumn(0).setMaxWidth(40);
            orderTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
            orderTable1.getColumnModel().getColumn(2).setMaxWidth(40);
            orderTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            orderTable1.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        CompleteButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CompleteButton1.setText("Complete");

        CancelButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CancelButton1.setText("Cancel");

        updateButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateButton1.setText("Update");

        waiterLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waiterLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        waiterLabel1.setText("Waiter:");

        waiterValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waiterValueLabel1.setText("Apurva Singh");

        orderTypeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderTypeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        orderTypeLabel1.setText("Type:");

        orderTypeValueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderTypeValueLabel1.setText("Take Away");

        totalLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalLabel1.setText("Total:");

        totalValueLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        customerLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerLabel2.setText("Customer:");

        customerValueLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerValueLabel2.setText("Apurva Singh");

        orderIdLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderIdLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        orderIdLabel2.setText("Order Id:");

        orderIdValueLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderIdValueLabel2.setText("12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CompleteButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalValueLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(waiterLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(waiterValueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(customerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customerValueLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderIdLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderTypeLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderIdValueLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderTypeValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waiterValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waiterLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(orderTypeLabel1)
                    .addComponent(orderTypeValueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderIdLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderIdValueLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addComponent(customerValueLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompleteButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalLabel1)
                    .addComponent(totalValueLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane.addTab("BT1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (parentFrame != null) {
            parentFrame.toFront();
            parentFrame.setEnabled(true);
        } else if (mainForm != null) {
            mainForm.toFront();
            mainForm.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private JTable createTable() {
        JTable orderTable = new JTable();
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "S.No.", "Name", "Qty", "Price"
                }
        ) {
            Class[] types = new Class[]{
                Integer.class, String.class, Integer.class, Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            orderTable.getColumnModel().getColumn(0).setMaxWidth(40);
            orderTable.getColumnModel().getColumn(2).setPreferredWidth(40);
            orderTable.getColumnModel().getColumn(2).setMaxWidth(40);
            orderTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            orderTable.getColumnModel().getColumn(3).setMaxWidth(80);
        }
        orderTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        return orderTable;
    }

    private int[] getOrderIdFromDB() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select id from `order` where status='Pending'", false);
        int[] id = null;
        try {
            int i = 0;
            connect.resultSet.last();
            id = new int[connect.resultSet.getRow()];

            connect.resultSet.beforeFirst();
            while (connect.resultSet.next()) {
                id[i] = connect.resultSet.getInt("id");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    private Object[][] getOrderDetailsFromDB(int orderId) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select m.name,od.quantity,od.price from menu m join "
                + "order_details od on m.id = od.menu_id and od.order_id = " + orderId, false);
        Object[][] items = null;
        try {
            int i = 0;
            connect.resultSet.last();
            items = new Object[connect.resultSet.getRow()][4];
            connect.resultSet.beforeFirst();
            while (connect.resultSet.next()) {
                items[i][0] = i + 1;
                items[i][1] = connect.resultSet.getString("name");
                items[i][2] = connect.resultSet.getInt("quantity");
                items[i][3] = connect.resultSet.getInt("price");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return items;
    }

    private String getTableNameFromDB(int orderId) {
        String tableName = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select name from `table` t join `order` o on o.table_id=t.id and o.id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                tableName = connect.resultSet.getString("name");
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tableName;
    }

    private String getStaffNameFromDB(int orderId) {
        String staffName = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select s.first_name,s.last_name from staff s join `order` o on o.staff_id=s.id and o.id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                staffName = connect.resultSet.getString("first_name") + " " + connect.resultSet.getString("last_name");
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return staffName;
    }

    private String getOrderTypeFromDB(int orderId) {
        String orderType = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select type from `order` where id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                orderType = connect.resultSet.getString("type");
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return orderType;
    }

    private int getCustomerIdFromDB(int orderId) {
        int id = 0;
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select customer_id from `order` where id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                id = connect.resultSet.getInt("customer_id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    private String getCustomerNameFromDB(int id) {
        String name = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select first_name,last_name from `customer` where id=" + id, false);
        try {
            if (connect.resultSet.next()) {
                name = connect.resultSet.getString("first_name") + " " + connect.resultSet.getString("last_name");
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return name;
    }

    private void createOrderPanel() {
        for (int id : getOrderIdFromDB()) {
            JPanel orderPanel = new JPanel();
            JTable orderTable = createTable();
            JScrollPane tableScrollPane = new JScrollPane();
            JLabel waiterLabel = new JLabel();
            JLabel waiterValueLabel = new JLabel();
            JLabel orderTypeLabel = new JLabel();
            JLabel orderTypeValueLabel = new JLabel();
            JLabel customerLabel = new JLabel();
            JLabel customerValueLabel = new JLabel();
            JLabel orderIdLabel = new JLabel();
            JLabel orderIdValueLabel = new JLabel();
            JLabel totalLabel = new JLabel();
            JLabel totalValueLabel = new JLabel();
            JButton completeButton = new JButton();
            JButton cancelButton = new JButton();
            JButton updateButton = new JButton();
            int customerId = getCustomerIdFromDB(id);
            Object[][] items = getOrderDetailsFromDB(id);
            DefaultTableModel dtm = (DefaultTableModel) orderTable.getModel();
            int totalPrice = 0;
            for (Object[] item : items) {
                dtm.addRow(item);
                totalPrice += (int) item[3];
            }

            tableScrollPane.setViewportView(orderTable);

            completeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            completeButton.setText("Complete");
            completeButton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    JButton btn = (JButton) evt.getSource();
                    if (btn.isEnabled()) {
                        alterOrder(id, "Completed", btn);
                    }
                }
            });

            cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            cancelButton.setText("Cancel");
            cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    JButton btn = (JButton) evt.getSource();
                    if (btn.isEnabled()) {
                        alterOrder(id, "Canceled", btn);
                    }
                }
            });

            updateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            updateButton.setText("Update");
            if (mainForm == null) {
                updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        JButton btn = (JButton) evt.getSource();
                        if (btn.isEnabled()) {
                            updateKot(btn, id);
                        }
                    }
                });
            } else {
                updateButton.setEnabled(false);
            }

            waiterLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            waiterLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            waiterLabel.setText("Waiter:");
            waiterLabel.setName("waiterLabel");

            waiterValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N            
            waiterValueLabel.setText(getStaffNameFromDB(id));
            waiterValueLabel.setName("waiterValueLabel");

            orderTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            orderTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            orderTypeLabel.setText("Type:");
            orderTypeLabel.setName("orderTypeLabel");

            orderTypeValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            orderTypeValueLabel.setText(getOrderTypeFromDB(id));
            orderTypeValueLabel.setName("orderTypeValueLabel");

            customerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            customerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            customerLabel.setText("Customer:");
            customerLabel.setName("customerLabel");

            customerValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            if (customerId == 0) {
                customerValueLabel.setText("Not selected");
            } else {
                customerValueLabel.setText(getCustomerNameFromDB(customerId));
            }

            customerValueLabel.setName("customerValueLabel");

            orderIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            orderIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            orderIdLabel.setText("Order Id:");
            orderIdLabel.setName("orderIdLabel");

            orderIdValueLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            orderIdValueLabel.setText(String.valueOf(id));
            orderIdValueLabel.setName("orderIdValueLabel");

            totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            totalLabel.setText("Total:");
            totalLabel.setName("totalLabel");

            totalValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N            
            totalValueLabel.setName("totalValueLabel");
            totalValueLabel.setText(String.valueOf(totalPrice));

            GroupLayout jPanelLayout = new GroupLayout(orderPanel);

            orderPanel.setLayout(jPanelLayout);
            jPanelLayout.setHorizontalGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                            .addComponent(completeButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(totalLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(totalValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                            .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                                            .addComponent(waiterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(waiterValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanelLayout.createSequentialGroup()
                                                            .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(customerValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(orderIdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(orderTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(orderIdValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(orderTypeValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                            .addContainerGap())
            );
            jPanelLayout.setVerticalGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(waiterValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(waiterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                    .addComponent(orderTypeLabel)
                                    .addComponent(orderTypeValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(customerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                    .addComponent(customerValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(orderIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(orderIdValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(completeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalLabel)
                                    .addComponent(totalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
            );
            jTabbedPane.addTab(getTableNameFromDB(id), orderPanel);
        }
    }

    private void alterOrder(int orderId, String status, JButton btn) {
        if (btn.isEnabled()) {
            if (JOptionPane.showConfirmDialog(null, "Are you sure you want this order to be " + status, "Alert", JOptionPane.YES_NO_OPTION) == 0) {
                DBConnect connect = new DBConnect();
                boolean cancelFlag = status.equals("Canceled");
                if (cancelFlag) {
                    String remarks = JOptionPane.showInputDialog("Please enter remarks why this order was canceled");
                    if (remarks != null) {
                        if (!remarks.equals("")) {
                            connect.insertStatement("update `order` set status='" + status + "',remarks='" + remarks + "' where id=" + orderId, false);
                            cancelFlag = false;
                        }
                    }
                } else {
                    connect.insertStatement("update `order` set status='" + status + "' where id=" + orderId, false);
                    createPayment(orderId);
                }
                if (!cancelFlag) {
                    connect.prepareStatement("select table_id from `order` where id=" + orderId, false);
                    try {
                        if (connect.resultSet.next()) {
                            int tableId = connect.resultSet.getInt("table_id");
                            connect.insertStatement("update `table` set occupied=0 where id=" + tableId, false);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Component[] components = btn.getParent().getComponents();
                    for (Component component : components) {
                        if (component instanceof JButton) {
                            component.setEnabled(false);
                        }
                    }
                    if (parentFrame != null) {
                        parentFrame.clearTable();
                    }
                }
            }
        }
    }

    private void updateKot(JButton btn, int orderId) {
        String tableName = jTabbedPane.getTitleAt(jTabbedPane.getSelectedIndex());
        String waiterName = "";
        String orderType = "";
        String customerName = "";
        for (Component component : btn.getParent().getComponents()) {
            if (component instanceof JLabel jLabel) {
                if (jLabel.getName().equals("waiterValueLabel")) {
                    waiterName = jLabel.getText();
                }
                if (jLabel.getName().equals("orderTypeValueLabel")) {
                    orderType = jLabel.getText();
                }
                if (jLabel.getName().equals("customerValueLabel")) {
                    String text = jLabel.getText();
                    if (!text.equals("Not selected")) {
                        customerName = text;
                    }
                }
            }
        }
        if (parentFrame != null) {
            parentFrame.setSelectedOrderId(orderId);
            parentFrame.updateMenuTable(updateButtonClicked(btn), tableName, waiterName, orderType, customerName);
            dispose();
        }
    }

    private void createPayment(int orderId) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select sum(price) as total from order_details where order_id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                int total = connect.resultSet.getInt("total");
                int customerId = getCustomerIdFromDB(orderId);
                if (customerId != 0) {
                    connect.insertStatement("insert into payment (order_id,amount,user_id,customer_id) "
                            + "values(" + orderId + "," + total + "," + parentFrame.loginId + "," + customerId + ")", false);
                } else {
                    connect.insertStatement("insert into payment (order_id,amount,user_id) values(" + orderId + "," + total + "," + parentFrame.loginId + ")", false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(KOTForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private Object[][] updateButtonClicked(JButton btn) {
        Object[][] items = null;
        for (var comp : btn.getParent().getComponents()) {
            if (comp instanceof JScrollPane jScrollPane) {
                JViewport viewport = jScrollPane.getViewport();
                JTable table = (JTable) viewport.getView();
                DefaultTableModel dtm = (DefaultTableModel) table.getModel();
                items = new Object[dtm.getRowCount()][dtm.getColumnCount()];
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    for (int j = 0; j < dtm.getColumnCount(); j++) {
                        items[i][j] = dtm.getValueAt(i, j);
                    }
                }
                break;
            }
        }
        return items;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KOTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KOTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KOTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KOTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KOTForm().setVisible(true);
            }
        });
    }

    POS parentFrame;
    MainForm mainForm;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton1;
    private javax.swing.JButton CompleteButton1;
    private javax.swing.JLabel customerLabel2;
    private javax.swing.JLabel customerValueLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel orderIdLabel2;
    private javax.swing.JLabel orderIdValueLabel2;
    private javax.swing.JTable orderTable1;
    private javax.swing.JLabel orderTypeLabel1;
    private javax.swing.JLabel orderTypeValueLabel1;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JLabel totalValueLabel2;
    private javax.swing.JButton updateButton1;
    private javax.swing.JLabel waiterLabel1;
    private javax.swing.JLabel waiterValueLabel1;
    // End of variables declaration//GEN-END:variables
}
