/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test1.luxcafe;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurva
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public MainForm() {
        initComponents();
        createDashboardPanel();
        setLocationRelativeTo(null);
        loginId = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        billListButton = new javax.swing.JButton();
        kitchenButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        tablesButton = new javax.swing.JButton();
        staffButton = new javax.swing.JButton();
        categoriesButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        dashboardPanel = new javax.swing.JPanel();
        topLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lux Cafe");
        setResizable(false);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("POS System");
        titleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleLabelMouseClicked(evt);
            }
        });

        orderButton.setText("POS");
        orderButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderButton.setMaximumSize(new java.awt.Dimension(110, 40));
        orderButton.setMinimumSize(new java.awt.Dimension(110, 40));
        orderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderButtonMouseClicked(evt);
            }
        });

        reportsButton.setText("Reports");
        reportsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportsButton.setMaximumSize(new java.awt.Dimension(110, 40));
        reportsButton.setMinimumSize(new java.awt.Dimension(110, 40));
        reportsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsButtonMouseClicked(evt);
            }
        });

        billListButton.setText("Bill");
        billListButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        billListButton.setMaximumSize(new java.awt.Dimension(110, 40));
        billListButton.setMinimumSize(new java.awt.Dimension(110, 40));
        billListButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billListButtonMouseClicked(evt);
            }
        });

        kitchenButton.setText("Order");
        kitchenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kitchenButton.setMaximumSize(new java.awt.Dimension(110, 40));
        kitchenButton.setMinimumSize(new java.awt.Dimension(110, 40));
        kitchenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitchenButtonMouseClicked(evt);
            }
        });

        menuButton.setText("Menu");
        menuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuButton.setMaximumSize(new java.awt.Dimension(110, 40));
        menuButton.setMinimumSize(new java.awt.Dimension(110, 40));
        menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonMouseClicked(evt);
            }
        });

        tablesButton.setText("Tables");
        tablesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tablesButton.setMaximumSize(new java.awt.Dimension(110, 40));
        tablesButton.setMinimumSize(new java.awt.Dimension(110, 40));
        tablesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesButtonMouseClicked(evt);
            }
        });

        staffButton.setText("Staff");
        staffButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffButton.setMaximumSize(new java.awt.Dimension(110, 40));
        staffButton.setMinimumSize(new java.awt.Dimension(110, 40));
        staffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffButtonMouseClicked(evt);
            }
        });

        categoriesButton.setText("Categories");
        categoriesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        categoriesButton.setMaximumSize(new java.awt.Dimension(110, 40));
        categoriesButton.setMinimumSize(new java.awt.Dimension(110, 40));
        categoriesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriesButtonMouseClicked(evt);
            }
        });

        customerButton.setText("Customer");
        customerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customerButton.setMaximumSize(new java.awt.Dimension(110, 40));
        customerButton.setMinimumSize(new java.awt.Dimension(110, 40));
        customerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerButtonMouseClicked(evt);
            }
        });

        userButton.setText("User");
        userButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userButton.setMaximumSize(new java.awt.Dimension(110, 40));
        userButton.setMinimumSize(new java.awt.Dimension(110, 40));
        userButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userButtonMouseClicked(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        topLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLabel1.setText("Dashboard");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lux-login-logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Restaurant Management System");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(topLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        loginLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginLabel.setText("Welcome User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reportsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kitchenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(staffButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tablesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoriesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(menuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                        .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(loginLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(billListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kitchenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tablesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(staffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonMouseClicked
        topLabel.setText("Menu");
        dashboardPanel.removeAll();
        createMenuTable();
        setMenuTable();
    }//GEN-LAST:event_menuButtonMouseClicked

    private void staffButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMouseClicked
        topLabel.setText("Staff");
        dashboardPanel.removeAll();
        createStaffTable();
        setStaffTable();
    }//GEN-LAST:event_staffButtonMouseClicked

    private void tablesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesButtonMouseClicked
        topLabel.setText("Tables");
        dashboardPanel.removeAll();
        createTableTable();
        setTableTable();
    }//GEN-LAST:event_tablesButtonMouseClicked

    private void categoriesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriesButtonMouseClicked
        topLabel.setText("Categories");
        dashboardPanel.removeAll();
        createCategoryTable();
        setCategoryTable();
    }//GEN-LAST:event_categoriesButtonMouseClicked

    private void orderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderButtonMouseClicked
        POS pos = new POS((MainForm) SwingUtilities.getWindowAncestor(dashboardPanel.getParent()));
        pos.loginId = loginId;
        pos.setVisible(true);
    }//GEN-LAST:event_orderButtonMouseClicked

    private void kitchenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitchenButtonMouseClicked
        if (checkDataExits("select count(*) as total from `order` where status='Pending'")) {
            KOTForm kot = new KOTForm((MainForm) SwingUtilities.getWindowAncestor(dashboardPanel.getParent()));
            kot.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No orders are pending", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_kitchenButtonMouseClicked

    private void customerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerButtonMouseClicked
        topLabel.setText("Customer");
        dashboardPanel.removeAll();
        createCustomerTable();
        setCustomerTable();
     }//GEN-LAST:event_customerButtonMouseClicked

    private void billListButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billListButtonMouseClicked
        if (checkDataExits("select count(*) as total from `payment`")) {
            BillForm billForm = new BillForm((MainForm) SwingUtilities.getWindowAncestor(((JButton) evt.getSource()).getParent()));
            billForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No bills are pending", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_billListButtonMouseClicked

    private void titleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseClicked
        createDashboardPanel();
    }//GEN-LAST:event_titleLabelMouseClicked

    private void userButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseClicked
        dashboardPanel.removeAll();
        topLabel.setText("User");
        createUserTable();
        setUserTable();
    }//GEN-LAST:event_userButtonMouseClicked

    private void reportsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsButtonMouseClicked
        ReportPanel reportPanel = new ReportPanel();
        dashboardPanel.removeAll();
        dashboardPanel.setLayout(new java.awt.CardLayout());
        dashboardPanel.add(reportPanel);
    }//GEN-LAST:event_reportsButtonMouseClicked

    private boolean checkDataExits(String statement) {
        boolean flag = true;
        DBConnect connect = new DBConnect();
        connect.prepareStatement(statement, false);
        try {
            if (connect.resultSet.next()) {
                flag = connect.resultSet.getInt("total") > 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;
    }

    public void setMenuTable() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from menu ", false);
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        try {
            while (connect.resultSet.next()) {
                int id = connect.resultSet.getInt("id");
                String name = connect.resultSet.getString("name");
                String description = connect.resultSet.getString("description");
                int price = connect.resultSet.getInt("price");
                String category = connect.resultSet.getString("category");
                Object[] rowData = {id, name, description, price, category};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setStaffTable() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from staff ", false);
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        try {
            while (connect.resultSet.next()) {
                int id = connect.resultSet.getInt("id");
                String firstName = connect.resultSet.getString("first_name");
                String lastName = connect.resultSet.getString("last_name");
                String position = connect.resultSet.getString("position");
                String phone = connect.resultSet.getString("phone");
                String email = connect.resultSet.getString("email");
                Object[] rowData = {id, firstName, lastName, position, phone, email};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setUserTable() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from `user` ", false);
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        try {
            while (connect.resultSet.next()) {
                int id = connect.resultSet.getInt("id");
                String firstName = connect.resultSet.getString("username");
                String lastName = connect.resultSet.getString("password");
                String position = connect.resultSet.getString("role");
                Object[] rowData = {id, firstName, lastName, position};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setTableTable() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from `table` ", false);
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        try {
            while (connect.resultSet.next()) {
                int id = connect.resultSet.getInt("id");
                String name = connect.resultSet.getString("name");
                String section = connect.resultSet.getString("section");
                int capacity = connect.resultSet.getInt("capacity");
                boolean occupied = connect.resultSet.getBoolean("occupied");
                Object[] rowData = {id, name, section, capacity, occupied};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setCategoryTable() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select category from menu group by category", false);
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        try {
            int sno = 1;
            while (connect.resultSet.next()) {
                String name = connect.resultSet.getString("category");
                Object[] rowData = {sno,name};
                model.addRow(rowData);
                sno ++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setCustomerTable() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from customer ", false);
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        try {
            while (connect.resultSet.next()) {
                int id = connect.resultSet.getInt("id");
                String firstName = connect.resultSet.getString("first_name");
                String lastName = connect.resultSet.getString("last_name");
                String phone = connect.resultSet.getString("phone");
                String email = connect.resultSet.getString("email");
                Object[] rowData = {id, firstName, lastName, phone, email};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void createMenuTable() {
        Class[] types = new Class[]{
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
        };
        String[] column = new String[]{"ID", "Name", "Description", "Price", "Category"};
        createTable(column, types, "menu");
        if (menuTable.getColumnModel().getColumnCount() > 0) {
            menuTable.getColumnModel().getColumn(0).setPreferredWidth(35);
            menuTable.getColumnModel().getColumn(0).setMaxWidth(35);
            menuTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            menuTable.getColumnModel().getColumn(2).setMaxWidth(80);
            menuTable.getColumnModel().getColumn(3).setPreferredWidth(40);
            menuTable.getColumnModel().getColumn(3).setMaxWidth(40);
            menuTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            menuTable.getColumnModel().getColumn(4).setMaxWidth(100);
        }
    }

    private void createStaffTable() {
        Class[] types = new Class[]{
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        String[] column = new String[]{"ID", "First Name", "Last Name", "Postion", "Phone", "Email"};
        createTable(column, types, "staff");
        if (menuTable.getColumnModel().getColumnCount() > 0) {
            menuTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            menuTable.getColumnModel().getColumn(0).setMaxWidth(40);
        }
    }

    private void createUserTable() {
        Class[] types = new Class[]{
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class};
        String[] column = new String[]{"ID", "User name", "Password", "Role"};
        createTable(column, types, "user");
        if (menuTable.getColumnModel().getColumnCount() > 0) {
            menuTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            menuTable.getColumnModel().getColumn(0).setMaxWidth(40);
        }
    }

    private void createCustomerTable() {
        Class[] types = new Class[]{
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        String[] column = new String[]{"ID", "First Name", "Last Name", "Phone", "Email"};
        createTable(column, types, "customer");
        if (menuTable.getColumnModel().getColumnCount() > 0) {
            menuTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            menuTable.getColumnModel().getColumn(0).setMaxWidth(40);
        }
    }

    private void createTableTable() {
        Class[] types = new Class[]{
            java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class};
        String[] column = new String[]{"ID", "Name", "Section", "Capacity", "Occupied"};
        createTable(column, types, "table");
        if (menuTable.getColumnModel().getColumnCount() > 0) {
            menuTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            menuTable.getColumnModel().getColumn(0).setMaxWidth(40);
        }
    }

    private void createCategoryTable() {
        Class[] types = new Class[]{
            java.lang.Integer.class, java.lang.String.class};
        String[] column = new String[]{"S.No", "Name"};
        createTable(column, types, "category");
        if (menuTable.getColumnModel().getColumnCount() > 0) {
            menuTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            menuTable.getColumnModel().getColumn(0).setMaxWidth(40);
        }
    }

    private void createTable(String[] column, Class[] types, String tableName) {
        menuTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        boolean[] canEdit = new boolean[column.length];
        for (int i = 0; i < column.length; i++) {
            canEdit[0] = false;
        }
        menuTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, column) {
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        menuTable.setColumnSelectionAllowed(false);
        menuTable.setShowGrid(true);
        menuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        menuTableScrollPane1.setViewportView(menuTable);

        JButton addButton = new JButton("Add");
        JButton updateButton = new JButton("Update");
        JButton deleteButton = new JButton("Delete");

        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switch (tableName) {
                    case "staff" -> {
                        AddStaffForm addStaffForm = new AddStaffForm((MainForm) SwingUtilities.getWindowAncestor(dashboardPanel.getParent()));
                        addStaffForm.setVisible(true);
                    }
                    case "menu" -> {
                        AddMenuForm addMenu = new AddMenuForm((MainForm) SwingUtilities.getWindowAncestor(dashboardPanel.getParent()));
                        addMenu.setVisible(true);
                    }
                    case "customer" -> {
                        AddCustomerForm customerForm = new AddCustomerForm((MainForm) SwingUtilities.getWindowAncestor(dashboardPanel.getParent()));
                        customerForm.setVisible(true);
                    }
                }
            }
        });
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (menuTable.getSelectedRow() != -1) {
                    switch (tableName) {
                        case "staff" -> {
                            updateStaffTable();
                        }
                        case "menu" -> {
                            updateMenuTable();
                        }
                        case "customer" -> {
                            updateCustomerTable();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please select an row", "Alert", JOptionPane.WARNING_MESSAGE);
                }
            }
        });
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (menuTable.getSelectedRow() != -1) {
                    int id = (int) menuTable.getValueAt(menuTable.getSelectedRow(), 0);
                    DBConnect connect = new DBConnect();
                    if (JOptionPane.showConfirmDialog(null, "Are you sure you want to delete "
                            + menuTable.getValueAt(menuTable.getSelectedRow(), 1), "Alert", JOptionPane.YES_NO_OPTION) == 0) {
                        connect.insertStatement("delete from " + tableName + " where id=" + id, false);
                        switch (tableName) {
                            case "staff" -> {
                                setStaffTable();
                            }
                            case "menu" -> {
                                setMenuTable();
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please select a row", "Alert", JOptionPane.WARNING_MESSAGE);
                }
            }
        });

        dashboardPanel.removeAll();
        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
                dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(topLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(menuTableScrollPane1)
                                .addContainerGap())
                        .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
                dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()
                                .addComponent(menuTableScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        if (tableName.equals("table") || tableName.equals("category") || tableName.equals("user")) {
            addButton.setVisible(false);
            updateButton.setVisible(false);
            deleteButton.setVisible(false);
        }
    }

    private void updateMenuTable() {
        AddMenuForm addMenu = new AddMenuForm((MainForm) SwingUtilities.getWindowAncestor(dashboardPanel.getParent()));
        addMenu.setVisible(true);
        int id = (int) menuTable.getValueAt(menuTable.getSelectedRow(), 0);
        String name = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 1);
        String description = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 2);
        int price = (int) menuTable.getValueAt(menuTable.getSelectedRow(), 3);
        int category;
        if ("Beverage".equals((String) menuTable.getValueAt(menuTable.getSelectedRow(), 4))) {
            category = 0;
        } else {
            category = 1;
        }
        addMenu.setFields(id, name, description, price, category);
    }

    private void updateStaffTable() {
        AddStaffForm addStaffForm = new AddStaffForm((MainForm) SwingUtilities.getWindowAncestor(dashboardPanel.getParent()));
        addStaffForm.setVisible(true);
        int id = (int) menuTable.getValueAt(menuTable.getSelectedRow(), 0);
        String firstName = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 1);
        String lastName = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 2);
        String postion = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 3);
        String phone = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 4);
        String email = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 5);
        addStaffForm.setFields(id, firstName, lastName, postion, phone, email);
    }

    private void updateCustomerTable() {
        AddCustomerForm customerForm = new AddCustomerForm((MainForm) SwingUtilities.getWindowAncestor(dashboardPanel.getParent()));
        customerForm.setVisible(true);
        int id = (int) menuTable.getValueAt(menuTable.getSelectedRow(), 0);
        String firstName = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 1);
        String lastName = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 2);
        String phone = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 3);
        String email = (String) menuTable.getValueAt(menuTable.getSelectedRow(), 4);
        customerForm.setFields(id, firstName, lastName, phone, email);
    }

    public void setUsernameFromDB(int id) {
        if (loginId != 0) {
            DBConnect connect = new DBConnect();
            connect.prepareStatement("select username from `user` where id=" + id, false);
            try {
                if (connect.resultSet.next()) {
                    loginLabel.setText("Welcome "+connect.resultSet.getString("username").toUpperCase());
                }
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void createDashboardPanel() {
        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.removeAll();
        topLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLabel.setText("Dashboard");
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lux-login-logo.png"))); // NOI18N
        logoTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoTextLabel.setText("Restaurant Management System");

        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
                dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logoTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(topLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashboardPanelLayout.setVerticalGroup(
                dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(logoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logoTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(134, Short.MAX_VALUE))
        );
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    javax.swing.JLabel logoLabel = new javax.swing.JLabel();
    javax.swing.JLabel logoTextLabel = new javax.swing.JLabel();
    javax.swing.JLabel topLabel = new javax.swing.JLabel();
    javax.swing.JScrollPane menuTableScrollPane1 = new javax.swing.JScrollPane();
    javax.swing.JTable menuTable = new javax.swing.JTable();

    int loginId = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billListButton;
    private javax.swing.JButton categoriesButton;
    private javax.swing.JButton customerButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton kitchenButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JButton staffButton;
    private javax.swing.JButton tablesButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel topLabel1;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
