/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test1.luxcafe;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurva
 */
public class POS extends JFrame {

    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
        menuScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        setMenuFromDB("select * from menu order by field('Hot Beverages','Cold Beverages')");
        setCategoryButton();
        setTableFromDB();
        setWaiterFromDB();
        setCustomerFromDB();
        setLocationRelativeTo(null);
        loginId = 1;  //delete on production
    }

    public POS(MainForm form) {
        parentFrame = form;
        parentFrame.setEnabled(false);
        initComponents();
        menuScrollPane.getVerticalScrollBar().setUnitIncrement(16);
        setMenuFromDB("select * from menu order by field('Hot Beverages','Cold Beverages')");
        setCategoryButton();
        setTableFromDB();
        setWaiterFromDB();
        setCustomerFromDB();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        kotButton = new javax.swing.JButton();
        placeOrderButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        categoryPanel = new javax.swing.JPanel();
        allCategoriesButton = new javax.swing.JButton();
        Beverages = new javax.swing.JButton();
        Bakery = new javax.swing.JButton();
        menuScrollPane = new javax.swing.JScrollPane();
        menuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        menuITableScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        waiterComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        orderTypeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tableComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POS System");

        newButton.setText("New");
        newButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newButtonMouseClicked(evt);
            }
        });

        billButton.setText("Bill");
        billButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billButtonMouseClicked(evt);
            }
        });

        kotButton.setText("Order");
        kotButton.setToolTipText("");
        kotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kotButtonMouseClicked(evt);
            }
        });

        placeOrderButton.setText("Place Order");
        placeOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placeOrderButtonMouseClicked(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        allCategoriesButton.setText("All Categories");
        allCategoriesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allCategoriesButtonMouseClicked(evt);
            }
        });

        Beverages.setText("Hot Beverage");
        Beverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BeveragesMouseClicked(evt);
            }
        });

        Bakery.setText("Bakery");
        Bakery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BakeryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout categoryPanelLayout = new javax.swing.GroupLayout(categoryPanel);
        categoryPanel.setLayout(categoryPanelLayout);
        categoryPanelLayout.setHorizontalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allCategoriesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
            .addComponent(Beverages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bakery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        categoryPanelLayout.setVerticalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allCategoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Beverages, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Bakery, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        menuScrollPane.setAutoscrolls(true);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Americano");
        jButton1.setToolTipText("90");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("cappchino");
        jButton2.setToolTipText("140");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuScrollPane.setViewportView(menuPanel);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Name", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menuTable.setSelectionForeground(new java.awt.Color(255, 255, 51));
        menuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        menuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        menuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTableMouseClicked(evt);
            }
        });
        menuTable.getModel().addTableModelListener(
            new TableModelListener() 
            {
                public void tableChanged(TableModelEvent evt) 
                {
                    isMenuTableCellChanged = true;
                }
            });
            menuITableScrollPane1.setViewportView(menuTable);
            if (menuTable.getColumnModel().getColumnCount() > 0) {
                menuTable.getColumnModel().getColumn(0).setPreferredWidth(40);
                menuTable.getColumnModel().getColumn(0).setMaxWidth(40);
                menuTable.getColumnModel().getColumn(2).setPreferredWidth(30);
                menuTable.getColumnModel().getColumn(2).setMaxWidth(30);
                menuTable.getColumnModel().getColumn(3).setPreferredWidth(100);
                menuTable.getColumnModel().getColumn(3).setMaxWidth(100);
            }

            jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel6.setText("Customer:");

            customerComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            customerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            customerComboBox.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    customerComboBoxItemStateChanged(evt);
                }
            });

            jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel5.setText("Waiter:");

            waiterComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            waiterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            waiterComboBox.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    waiterComboBoxItemStateChanged(evt);
                }
            });

            jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel3.setText("Order Type:");

            orderTypeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            orderTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine In", "Delivery", "Take Away" }));
            orderTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    orderTypeComboBoxItemStateChanged(evt);
                }
            });

            jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel4.setText("Table No:");

            tableComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            tableComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

            jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jLabel2.setText("Total:");

            totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            totalLabel.setText("0");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(categoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(orderTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(menuITableScrollPane1)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(billButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(placeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(waiterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waiterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3)
                                .addComponent(jSeparator4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(menuITableScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(orderTypeComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(categoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(15, Short.MAX_VALUE))))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void newButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseClicked
        clearTable();
        orderTypeComboBox.setSelectedIndex(0);
        orderTypeChanged = false;
    }//GEN-LAST:event_newButtonMouseClicked

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        totalLabel.setText("0");
        setTableFromDB();
        setWaiterFromDB();
        setCustomerFromDB();
        selectedOrderId = 0;
    }

    private void allCategoriesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allCategoriesButtonMouseClicked
        setMenuFromDB("select * from menu");
    }//GEN-LAST:event_allCategoriesButtonMouseClicked

    private void menuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTableMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            DefaultTableModel dtm = (DefaultTableModel) menuTable.getModel();
            int selectedRow = menuTable.getSelectedRow();
            int qty = (int) dtm.getValueAt(selectedRow, 2);
            if (qty > 1) {
                int unitPrice = (int) dtm.getValueAt(selectedRow, 3) / qty;
                int totalPrice = (int) dtm.getValueAt(selectedRow, 3) - unitPrice;
                dtm.setValueAt(totalPrice, selectedRow, 3);
                dtm.setValueAt(qty - 1, selectedRow, 2);
            } else {
                dtm.removeRow(selectedRow);
            }
            int total = 0;
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.setValueAt(i + 1, i, 0);
                total += (int) dtm.getValueAt(i, 3);
            }
            totalLabel.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_menuTableMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setOrder(jButton1.getText(), Integer.parseInt(jButton1.getToolTipText()));
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        setOrder(jButton2.getText(), Integer.parseInt(jButton2.getToolTipText()));
    }//GEN-LAST:event_jButton2MouseClicked

    private void BakeryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BakeryMouseClicked
        setMenuFromDB("select * from menu where category='Bakery'");
    }//GEN-LAST:event_BakeryMouseClicked

    private void placeOrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeOrderButtonMouseClicked
        if (checkKotRequiremnets()) {
            DBConnect connect = new DBConnect();
            int tableId = getIdFromTable(tableComboBox.getSelectedItem().toString());
            int waiterId = getIdFromStaff(waiterComboBox.getSelectedItem().toString());
            int customerId = getIDFromCustomer(customerComboBox.getSelectedItem().toString());
            String orderType = orderTypeComboBox.getSelectedItem().toString();
            if (tableId != 0 && waiterId != 0) {
                if (selectedOrderId == 0) {
                    orderTypeChanged = false;
                    waiterChanged = false;
                    customerChanged = false;
                    if (customerId != 0) {
                        connect.insertStatement("insert into `order`(staff_id,status,table_id,type,customer_id) "
                                + "values(" + waiterId + ",'Pending'," + tableId + ",'" + orderType + "'," + customerId + ") ", false);
                    } else {
                        connect.insertStatement("insert into `order`(staff_id,status,table_id,type) "
                                + "values(" + waiterId + ",'Pending'," + tableId + ",'" + orderType + "') ", false);
                    }
                    try {
                        if (connect.resultSet.next()) {
                            int orderId = connect.resultSet.getInt(1);
                            insertOrderDetails(connect, orderId, tableId);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    if (orderTypeChanged) {
                        connect.insertStatement("update `order` set type='"
                                + orderTypeComboBox.getSelectedItem().toString() + "' where id=" + selectedOrderId, false);
                        orderTypeChanged = false;
                    }
                    if (waiterChanged) {
                        connect.insertStatement("update `order` set staff_id=" + waiterId + " where id=" + selectedOrderId, false);
                        waiterChanged = false;
                    }
                    if (customerChanged && customerId != 0) {
                        connect.insertStatement("update `order` set customer_id=" + customerId + " where id=" + selectedOrderId, false);
                        customerChanged = false;
                        JOptionPane.showMessageDialog(null, "Order successfully updated", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    }

                    try {
                        if (isMenuTableCellChanged) {
                            insertOrderDetails(connect, selectedOrderId, tableId);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_placeOrderButtonMouseClicked

    private void insertOrderDetails(DBConnect connect, int orderId, int tableId) throws SQLException {
        if (selectedOrderId != 0) {
            connect.insertStatement("delete from order_details where order_id=" + orderId, false);
        }
        for (int i = 0; i < menuTable.getRowCount(); i++) {
            String name = String.valueOf(menuTable.getValueAt(i, 1));
            int menuId = getIdFromMenu(name);
            int qty = (int) menuTable.getValueAt(i, 2);
            int price = (int) menuTable.getValueAt(i, 3);
            connect.insertStatement("insert into order_details(order_id,menu_id,quantity,price) "
                    + "values(" + orderId + "," + menuId + "," + qty + "," + price + ")", false);
        }
        if (connect.resultSet.next()) {
            connect.insertStatement("update `table` set occupied=1 where id =" + tableId, false);
            JOptionPane.showMessageDialog(null, "Order successfully placed", "Alert", JOptionPane.INFORMATION_MESSAGE);
            isMenuTableCellChanged = false;
            tableComboBox.setModel(new DefaultComboBoxModel<>(new String[]{tableComboBox.getSelectedItem().toString()}));
            waiterComboBox.removeItem("Select a name");
            if (customerChanged && !customerComboBox.getSelectedItem().toString().equals("Select a name")) {
                customerComboBox.removeItem("Select a name");
            }
            selectedOrderId = orderId;
        }
    }

    private void billButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billButtonMouseClicked
        if (checkDataExits("select count(*) as total from `payment`")) {
            BillForm billForm = new BillForm((POS) SwingUtilities.getWindowAncestor(((JButton) evt.getSource()).getParent()));
            billForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No bills are pending", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_billButtonMouseClicked

    private void kotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kotButtonMouseClicked
        if (checkDataExits("select count(*) as total from `order` where status='Pending'")) {
            KOTForm kotForm = new KOTForm((POS) SwingUtilities.getWindowAncestor(((JButton) evt.getSource()).getParent()));
            kotForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No orders are pending", "Alert", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_kotButtonMouseClicked

    private void orderTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_orderTypeComboBoxItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            orderTypeChanged = true;
        }
    }//GEN-LAST:event_orderTypeComboBoxItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (parentFrame != null) {
            parentFrame.toFront();
            parentFrame.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void waiterComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_waiterComboBoxItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            waiterChanged = true;
        }
    }//GEN-LAST:event_waiterComboBoxItemStateChanged

    private void customerComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerComboBoxItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            customerChanged = true;
        }
    }//GEN-LAST:event_customerComboBoxItemStateChanged

    private void BeveragesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BeveragesMouseClicked
        setMenuFromDB("select * from menu where category='Beverage'");
    }//GEN-LAST:event_BeveragesMouseClicked

    private boolean checkDataExits(String statement) {
        boolean flag = true;
        DBConnect connect = new DBConnect();
        connect.prepareStatement(statement, false);
        try {
            if (connect.resultSet.next()) {
                flag = connect.resultSet.getInt("total") > 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;
    }

    private int getIdFromTable(String name) {
        return getIdFromDB("select id from `table` where name='" + name + "'");
    }

    private int getIdFromStaff(String n) {
        String[] name = n.split(" ");
        return getIdFromDB("select id from staff where first_name='" + name[0] + "' and last_name='" + name[1] + "'");
    }

    private int getIDFromCustomer(String n) {
        String[] name = n.split(" ");
        return getIdFromDB("select id from customer where first_name='" + name[0] + "' and last_name='" + name[1] + "'");
    }

    private int getIdFromMenu(String name) {
        return getIdFromDB("select id from menu where name='" + name + "'");
    }

    private int getIdFromDB(String statement) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement(statement, false);
        int id = 0;
        try {
            while (connect.resultSet.next()) {
                id = connect.resultSet.getInt("id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    private boolean checkKotRequiremnets() {
        boolean flag;
        if (tableComboBox.getSelectedItem() == "Select a table") {
            JOptionPane.showMessageDialog(null, "Please select a table", "Alert", JOptionPane.WARNING_MESSAGE);
            flag = false;
        } else if (waiterComboBox.getSelectedItem() == "Select a name") {
            JOptionPane.showMessageDialog(null, "Please select a waiter", "Alert", JOptionPane.WARNING_MESSAGE);
            flag = false;
        } else if (menuTable.getRowCount() < 1) {
            JOptionPane.showMessageDialog(null, "Please add an item", "Alert", JOptionPane.WARNING_MESSAGE);
            flag = false;
        } else if (waiterChanged) {
            flag = true;
        } else if (customerChanged) {
            flag = true;
        } else {
            flag = isMenuTableCellChanged;
        }
        return flag;
    }

    private void setMenuFromDB(String statement) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement(statement, false);
        GroupLayout menuPanelLayout = new GroupLayout(menuPanel);
        menuPanel.removeAll();
        menuPanel.setLayout(menuPanelLayout);
        var parallelGroup = menuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING);
        var seqGroup = menuPanelLayout.createSequentialGroup();
        seqGroup.addContainerGap();
        try {
            while (connect.resultSet.next()) {
                String name = connect.resultSet.getString("name");
                int price = connect.resultSet.getInt("price");
                JButton menuButton = new JButton(name);
                menuButton.setFont(new java.awt.Font("Segoe UI", 0, 14));
                menuButton.setToolTipText(String.valueOf(price));
                menuButton.setPreferredSize(new java.awt.Dimension(122, 32));
                menuButton.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        setOrder(name, price);
                    }
                });
                parallelGroup.addGroup(menuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(menuPanelLayout.createSequentialGroup().addContainerGap()
                                .addComponent(menuButton, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)));
                seqGroup.addComponent(menuButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE);
//                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED);                

            }
            menuPanelLayout.setHorizontalGroup(
                    menuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                    .addGroup(parallelGroup).addContainerGap()));
            menuPanelLayout.setVerticalGroup(
                    menuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(seqGroup.addContainerGap()));
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private ArrayList getCategoryListFromDB() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select category from menu group by category order by field('Hot Beverages','Cold Beverages')", false);
        ArrayList list = new ArrayList();
        list.add("All Category");
        try {
            while (connect.resultSet.next()) {
                list.add(connect.resultSet.getString("category"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }

    private void setCategoryButton() {
        categoryPanel.removeAll();
        javax.swing.GroupLayout categoryPanelLayout = new javax.swing.GroupLayout(categoryPanel);
        categoryPanel.setLayout(categoryPanelLayout);
        GroupLayout.ParallelGroup parallelGroup = categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        GroupLayout.SequentialGroup sequentialGroup = categoryPanelLayout.createSequentialGroup();
        for (Object item : getCategoryListFromDB()) {
            if (item != null) {
                String category = (String) item;
                JButton button = new JButton();
                button.setText(category);
                button.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        if (category.equals("All Category")) {
                            setMenuFromDB("select * from menu");
                        } else {
                            setMenuFromDB("select * from menu where category='" + category + "'");
                        }
                    }
                });

                parallelGroup
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE);
                sequentialGroup.addContainerGap()
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE);
            }
        }
        categoryPanelLayout.setHorizontalGroup(
                categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(parallelGroup).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        sequentialGroup.addContainerGap();
        categoryPanelLayout.setVerticalGroup(
                categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sequentialGroup));
    }

    private void setOrder(String name, int amount) {
        DefaultTableModel dtm = (DefaultTableModel) menuTable.getModel();
        int rowCount = menuTable.getRowCount();
        int sno = rowCount + 1;
        String item = name;
        int qty = 1;
        int price = amount;
        int total = 0;
        if (rowCount > 0) {
            boolean rowFound = false;
            for (int i = 0; i < rowCount; i++) {
                if (menuTable.getValueAt(i, 1).equals(item)) {
                    qty += (int) menuTable.getValueAt(i, 2);
                    price += (int) menuTable.getValueAt(i, 3);
                    menuTable.setValueAt(qty, i, 2);
                    menuTable.setValueAt(price, i, 3);
                    rowFound = true;
                    break;
                }
            }
            if (!rowFound) {
                Object[] rowData = {sno, item, qty, price};
                dtm.addRow(rowData);
            }
        } else {
            Object[] rowData = {sno, item, qty, price};
            dtm.addRow(rowData);
        }
        for (int i = 0; i < menuTable.getRowCount(); i++) {
            total += (int) menuTable.getValueAt(i, 3);
        }
        totalLabel.setText(String.valueOf(total) + "/-");
    }

    private void setTableFromDB() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from `table` where occupied=0", false);
        DefaultComboBoxModel comboBox = new DefaultComboBoxModel<>();
        comboBox.addElement("Select a table");
        try {
            while (connect.resultSet.next()) {
                String tableName = connect.resultSet.getString("name");
                comboBox.addElement(tableName);
            }
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableComboBox.setModel(comboBox);
    }

    private void setWaiterFromDB() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from staff", false);
        DefaultComboBoxModel comboBox = new DefaultComboBoxModel<>();
        comboBox.addElement("Select a name");
        try {
            while (connect.resultSet.next()) {
                String firstName = connect.resultSet.getString("first_name");
                String lastName = connect.resultSet.getString("last_name");
                comboBox.addElement(firstName + " " + lastName);
            }
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        waiterComboBox.setModel(comboBox);
    }

    private void setCustomerFromDB() {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from customer", false);
        DefaultComboBoxModel comboBox = new DefaultComboBoxModel<>();
        comboBox.addElement("Select a name");
        try {
            while (connect.resultSet.next()) {
                String firstName = connect.resultSet.getString("first_name");
                String lastName = connect.resultSet.getString("last_name");
                comboBox.addElement(firstName + " " + lastName);
            }
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        customerComboBox.setModel(comboBox);
    }

    public void setSelectedOrderId(int orderId) {
        selectedOrderId = orderId;
    }

    public int getOrderId() {
        return selectedOrderId;
    }

    public void updateMenuTable(Object[][] items, String tableName, String waiterName, String orderType, String customerName) {
        tableComboBox.removeAllItems();
        tableComboBox.addItem(tableName);
        waiterComboBox.removeItem("Select a name");
        waiterComboBox.setSelectedItem(waiterName);
        orderTypeComboBox.setSelectedItem(orderType);
        waiterChanged = false;
        orderTypeChanged = false;
        if (!customerName.equals("")) {
            customerComboBox.removeItem("Select a name");
            customerComboBox.setSelectedItem(customerName);
            customerChanged = false;
        } else {
            setCustomerFromDB();
        }
        DefaultTableModel dtm = (DefaultTableModel) menuTable.getModel();
        dtm.setRowCount(0);
        int total = 0;
        for (Object[] item : items) {
            dtm.addRow(item);
            total += (int) item[3];
        }
        totalLabel.setText(String.valueOf(total));
        waiterChanged = false;
        orderTypeChanged = false;
        isMenuTableCellChanged = false;
    }

    public void setUsernameFromDB(int id) {
        if (loginId != 0) {
            DBConnect connect = new DBConnect();
            connect.prepareStatement("select username from `user` where id=" + id, false);
            try {
                if (connect.resultSet.next()) {
                    jLabel1.setText(connect.resultSet.getString("username").toUpperCase());
                }
            } catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    private boolean isMenuTableCellChanged = false;
    private int selectedOrderId = 0;
    private boolean orderTypeChanged = false;
    private boolean waiterChanged = false;
    private boolean customerChanged = false;

    MainForm parentFrame;
    int loginId;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bakery;
    private javax.swing.JButton Beverages;
    private javax.swing.JButton allCategoriesButton;
    private javax.swing.JButton billButton;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JComboBox<String> customerComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton kotButton;
    private javax.swing.JScrollPane menuITableScrollPane1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JTable menuTable;
    private javax.swing.JButton newButton;
    private javax.swing.JComboBox<String> orderTypeComboBox;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JComboBox<String> tableComboBox;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JComboBox<String> waiterComboBox;
    // End of variables declaration//GEN-END:variables
}
