/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.test1.luxcafe;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurva
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
        setDsrReport();
        setCreditReport();
        setSalesReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dsrPanel = new javax.swing.JPanel();
        dsrComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dsrComboBox2 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsrTable = new javax.swing.JTable();
        dsrGetButton = new javax.swing.JButton();
        salesPanel = new javax.swing.JPanel();
        salesComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salesComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        salesDayComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salesMonthComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        salesYearComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        salesDayComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        salesMonthComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        salesYearComboBox2 = new javax.swing.JComboBox<>();
        salesGetButton = new javax.swing.JButton();
        creditorPanel = new javax.swing.JPanel();
        creditComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        creditTable = new javax.swing.JTable();
        creditGetButton = new javax.swing.JButton();
        creditBackButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Report");

        dsrComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dine In", "Delivery", "Take Away" }));

        jLabel2.setText("Order Type :");

        jLabel3.setText("Payment Type :");

        dsrComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cash", "QR", "Credit" }));

        dsrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Bill Id", "Amount", "Discount", "Recevied", "Order", "Payment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dsrTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        dsrTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsrTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsrTable);
        if (dsrTable.getColumnModel().getColumnCount() > 0) {
            dsrTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            dsrTable.getColumnModel().getColumn(0).setMaxWidth(40);
            dsrTable.getColumnModel().getColumn(1).setPreferredWidth(40);
            dsrTable.getColumnModel().getColumn(1).setMaxWidth(40);
        }

        dsrGetButton.setBackground(new java.awt.Color(204, 255, 204));
        dsrGetButton.setForeground(new java.awt.Color(153, 0, 0));
        dsrGetButton.setText("Get");
        dsrGetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsrGetButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dsrPanelLayout = new javax.swing.GroupLayout(dsrPanel);
        dsrPanel.setLayout(dsrPanelLayout);
        dsrPanelLayout.setHorizontalGroup(
            dsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsrComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dsrGetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsrComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(dsrPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        dsrPanelLayout.setVerticalGroup(
            dsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dsrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dsrComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(dsrComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dsrGetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("DSR", dsrPanel);

        salesComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dine In", "Delivery", "Take Away" }));

        jLabel4.setText("Order Type :");

        jLabel5.setText("Payment Type :");

        salesComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cash", "QR", "Credit" }));

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "1", "2000", null, null, "2024/02/04", "Credit"}
            },
            new String [] {
                "S.No.", "Bill Id", "Amount", "Discount", "Received", "Date", "P Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        salesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(salesTable);
        if (salesTable.getColumnModel().getColumnCount() > 0) {
            salesTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            salesTable.getColumnModel().getColumn(0).setMaxWidth(40);
            salesTable.getColumnModel().getColumn(1).setPreferredWidth(45);
            salesTable.getColumnModel().getColumn(1).setMaxWidth(45);
        }

        jLabel6.setText("From :");

        salesDayComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel7.setText("Day");

        jLabel8.setText("Month");

        salesMonthComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April" }));
        salesMonthComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                salesMonthComboBox1ItemStateChanged(evt);
            }
        });

        jLabel9.setText("Year");

        salesYearComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025" }));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("To :");

        jLabel11.setText("Day");

        salesDayComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel12.setText("Month");

        salesMonthComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April" }));
        salesMonthComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                salesMonthComboBox2ItemStateChanged(evt);
            }
        });

        jLabel13.setText("Year");

        salesYearComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025" }));

        salesGetButton.setBackground(new java.awt.Color(204, 255, 204));
        salesGetButton.setForeground(new java.awt.Color(153, 0, 0));
        salesGetButton.setText("Get");
        salesGetButton.setMinimumSize(new java.awt.Dimension(65, 23));
        salesGetButton.setPreferredSize(new java.awt.Dimension(65, 23));
        salesGetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesGetButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salesPanelLayout = new javax.swing.GroupLayout(salesPanel);
        salesPanel.setLayout(salesPanelLayout);
        salesPanelLayout.setHorizontalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(salesPanelLayout.createSequentialGroup()
                        .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, salesPanelLayout.createSequentialGroup()
                                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(salesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salesDayComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salesMonthComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salesYearComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(salesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salesDayComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salesMonthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salesYearComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, salesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salesComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(salesGetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salesComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        salesPanelLayout.setVerticalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(salesComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salesGetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(salesComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salesDayComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(salesMonthComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(salesYearComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salesDayComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(salesMonthComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(salesYearComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sales", salesPanel);

        creditComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dine In", "Delivery", "Take Away" }));

        jLabel14.setText("Order Type :");

        jLabel15.setText("Payment Type : Credit");

        creditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "First Name", "Last Name", "Mobile", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        creditTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        creditTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(creditTable);
        if (creditTable.getColumnModel().getColumnCount() > 0) {
            creditTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            creditTable.getColumnModel().getColumn(0).setMaxWidth(40);
            creditTable.getColumnModel().getColumn(4).setPreferredWidth(80);
            creditTable.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        creditGetButton.setBackground(new java.awt.Color(204, 255, 204));
        creditGetButton.setForeground(new java.awt.Color(153, 0, 0));
        creditGetButton.setText("Get");
        creditGetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditGetButtonMouseClicked(evt);
            }
        });

        creditBackButton.setBackground(new java.awt.Color(204, 255, 204));
        creditBackButton.setForeground(new java.awt.Color(153, 0, 0));
        creditBackButton.setText("Back");
        creditBackButton.setEnabled(false);
        creditBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditBackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout creditorPanelLayout = new javax.swing.GroupLayout(creditorPanel);
        creditorPanel.setLayout(creditorPanelLayout);
        creditorPanelLayout.setHorizontalGroup(
            creditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(creditorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(creditorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditGetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addContainerGap())))
        );
        creditorPanelLayout.setVerticalGroup(
            creditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(creditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(creditGetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Credit", creditorPanel);

        printButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        printButton.setText("Print");
        printButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(printButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dsrGetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsrGetButtonMouseClicked
        String orderType = (String) dsrComboBox1.getSelectedItem();
        String paymentType = (String) dsrComboBox2.getSelectedItem();
        String statement = "SELECT p.* FROM `payment` p JOIN `order` o ON o.`id` = p.`order_id` WHERE p.payment_date >= CURRENT_DATE";
        if (!orderType.equals("Select")) {
            statement += " AND o.`type` = '" + orderType + "'";
        }
        if (!paymentType.equals("Select")) {
            statement += " AND p.`payment_type` = '" + paymentType + "'";
        }
        getDsrReportData(statement);
    }//GEN-LAST:event_dsrGetButtonMouseClicked

    private void salesGetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesGetButtonMouseClicked
        String orderType = (String) salesComboBox1.getSelectedItem();
        String paymentType = (String) salesComboBox2.getSelectedItem();
        String fromDate = ((String) salesYearComboBox1.getSelectedItem()) + "-" + (String.valueOf(salesMonthComboBox1.getSelectedIndex() + 1))
                + "-" + ((String) salesDayComboBox1.getSelectedItem());
        String toDate = ((String) salesYearComboBox2.getSelectedItem()) + "-" + (String.valueOf(salesMonthComboBox2.getSelectedIndex() + 1))
                + "-" + ((String) salesDayComboBox2.getSelectedItem());

        String statement = "select p.* from payment p ";
        if (!orderType.equals("Select")) {
            statement += " JOIN `order` o ON o.`id` = p.`order_id` where o.`type` = '" + orderType + "' and";
        } else {
            statement += "where";
        }
        statement += " p.status = 'Completed' and p.payment_date between '" + fromDate + "' and '" + toDate + " 23:59:59'";
        if (!paymentType.equals("Select")) {
            statement += " AND p.`payment_type` = '" + paymentType + "'";
        }
        getSalesReportData(statement);
    }//GEN-LAST:event_salesGetButtonMouseClicked

    private void creditGetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditGetButtonMouseClicked
        if (creditGetButton.isEnabled()) {
            String orderType = (String) creditComboBox.getSelectedItem();
            if (!orderType.equals("Select")) {
                String statement = "SELECT c.*,SUM(p.amount) AS amount FROM customer c JOIN payment p ON "
                        + "p.`customer_id` = c.`id` JOIN `order` o ON o.`id` = p.`order_id`"
                        + " WHERE p.`payment_type` = 'Credit' AND o.`type` = '" + orderType + "' GROUP BY c.`id`";
                getCreditReportData(statement);
            } else {
                setCreditReport();
            }
        }
    }//GEN-LAST:event_creditGetButtonMouseClicked
    boolean comboTriggerFlag = false;
    private void salesMonthComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_salesMonthComboBox1ItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            int monthIndex = salesMonthComboBox1.getSelectedIndex();
            var time = LocalDate.now();
            if (comboTriggerFlag) {
                if (time.getMonthValue() > monthIndex + 1) {
                    YearMonth yearMonthObject = YearMonth.of(Integer.parseInt(salesYearComboBox1.getSelectedItem().toString()), monthIndex + 1);
                    salesDayComboBox1.removeAllItems();
                    for (int i = 0; i < yearMonthObject.lengthOfMonth(); i++) {
                        salesDayComboBox1.addItem(String.valueOf(i + 1));
                    }
                } else if (time.getMonthValue() == monthIndex + 1 && salesDayComboBox1.getItemCount() != time.getDayOfMonth()) {
                    salesDayComboBox1.removeAllItems();
                    for (int i = 0; i < time.getDayOfMonth(); i++) {
                        salesDayComboBox1.addItem(String.valueOf(i + 1));
                    }
                }
            }
        }
    }//GEN-LAST:event_salesMonthComboBox1ItemStateChanged

    private void salesMonthComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_salesMonthComboBox2ItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            int monthIndex = salesMonthComboBox2.getSelectedIndex();
            var time = LocalDate.now();
            if (comboTriggerFlag) {
                if (time.getMonthValue() > monthIndex + 1) {
                    YearMonth yearMonthObject = YearMonth.of(Integer.parseInt(salesYearComboBox2.getSelectedItem().toString()), monthIndex + 1);
                    salesDayComboBox2.removeAllItems();
                    for (int i = 0; i < yearMonthObject.lengthOfMonth(); i++) {
                        salesDayComboBox2.addItem(String.valueOf(i + 1));
                    }
                    salesMonthComboBox1.removeAllItems();
                    for (int i = 0; i <= salesMonthComboBox2.getSelectedIndex(); i++) {
                        salesMonthComboBox1.addItem(salesMonthComboBox2.getItemAt(i));
                    }
                    salesMonthComboBox1.setSelectedIndex(salesMonthComboBox2.getSelectedIndex());
                } else if (time.getMonthValue() == monthIndex + 1 && salesDayComboBox2.getItemCount() != time.getDayOfMonth()) {
                    salesDayComboBox2.removeAllItems();
                    for (int i = 0; i < time.getDayOfMonth(); i++) {
                        salesDayComboBox2.addItem(String.valueOf(i + 1));
                    }
                    salesMonthComboBox1.removeAllItems();
                    for (int i = 0; i <= salesMonthComboBox2.getSelectedIndex(); i++) {
                        salesMonthComboBox1.addItem(salesMonthComboBox2.getItemAt(i));
                    }
                    salesMonthComboBox1.setSelectedIndex(salesMonthComboBox2.getSelectedIndex());
                }
            }
        }
    }//GEN-LAST:event_salesMonthComboBox2ItemStateChanged

    private void dsrTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsrTableMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int selectedRowIndex = dsrTable.getSelectedRow();
            if (dsrTable.getRowCount() - 4 > selectedRowIndex) {
                String billId = String.valueOf(dsrTable.getValueAt(selectedRowIndex, 1));
                String amount = String.valueOf(dsrTable.getValueAt(selectedRowIndex, 2));
                String discount = String.valueOf(dsrTable.getValueAt(selectedRowIndex, 3));
                String recevied = String.valueOf(dsrTable.getValueAt(selectedRowIndex, 4));
                String orderType = (String) dsrTable.getValueAt(selectedRowIndex, 5);
                String paymentType = (String) dsrTable.getValueAt(selectedRowIndex, 6);
                String date = LocalDate.now().toString();
                ReportDetailsForm rdf = new ReportDetailsForm();
                rdf.setTitle("Daily Sales Report Details");
                rdf.setData(billId, amount, discount, recevied, orderType, paymentType, date);
                rdf.setVisible(true);
            }
        }
    }//GEN-LAST:event_dsrTableMouseClicked

    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int selectedRowIndex = salesTable.getSelectedRow();
            if (salesTable.getRowCount() - 4 > selectedRowIndex) {
                String billId = String.valueOf(salesTable.getValueAt(selectedRowIndex, 1));
                String amount = String.valueOf(salesTable.getValueAt(selectedRowIndex, 2));
                String discount = String.valueOf(salesTable.getValueAt(selectedRowIndex, 3));
                String recevied = String.valueOf(salesTable.getValueAt(selectedRowIndex, 4));
                String orderType = getOrderTypefromDB(getOrderIdFromDB(Integer.parseInt(billId)));
                String paymentType = (String) salesTable.getValueAt(selectedRowIndex, 6);
                String date = (String) salesTable.getValueAt(selectedRowIndex, 5);
                ReportDetailsForm rdf = new ReportDetailsForm();
                rdf.setTitle("Sales Report Details");
                rdf.setData(billId, amount, discount, recevied, orderType, paymentType, date);
                rdf.setVisible(true);
            }
        }
    }//GEN-LAST:event_salesTableMouseClicked

    private void creditTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditTableMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            if (creditGetButton.isEnabled()) {
                int selectedRowIndex = creditTable.getSelectedRow();
                if (creditTable.getRowCount() - 2 > selectedRowIndex) {
                    String firstName = (String) creditTable.getValueAt(selectedRowIndex, 1);
                    String lastName = (String) creditTable.getValueAt(selectedRowIndex, 2);
                    String mobile = (String) creditTable.getValueAt(selectedRowIndex, 3);
                    tempTableModel = (DefaultTableModel) creditTable.getModel();
                    creditTable.removeAll();
                    creditTable.setModel(salesTable.getModel());
                    DefaultTableModel dtm = (DefaultTableModel) creditTable.getModel();
                    creditTable.getColumnModel().getColumn(creditTable.getColumnCount() - 1).setHeaderValue("Order");
                    dtm.setRowCount(0);
                    setSecondCreditTable(getCustomerIdFromDB(firstName, lastName, mobile));
                    creditBackButton.setEnabled(true);
                    creditGetButton.setEnabled(false);
                }
            } else {
                int selectedRowIndex = creditTable.getSelectedRow();
                if (creditTable.getRowCount() - 4 > selectedRowIndex) {
                    String billId = String.valueOf(creditTable.getValueAt(selectedRowIndex, 1));
                    String amount = String.valueOf(creditTable.getValueAt(selectedRowIndex, 2));
                    String discount = String.valueOf(creditTable.getValueAt(selectedRowIndex, 3));
                    String recevied = String.valueOf(creditTable.getValueAt(selectedRowIndex, 4));
                    String orderType = getOrderTypefromDB(getOrderIdFromDB(Integer.parseInt(billId)));
                    String paymentType = (String) creditTable.getValueAt(selectedRowIndex, 6);
                    String date = (String) creditTable.getValueAt(selectedRowIndex, 5);
                    ReportDetailsForm rdf = new ReportDetailsForm();
                    rdf.setTitle("Credit Report Details");
                    rdf.setData(billId, amount, discount, recevied, orderType, paymentType, date);
                    rdf.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_creditTableMouseClicked

    private void setSecondCreditTable(int customerId) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select * from payment where customer_id=" + customerId, false);
        try {
            int sno = 1;
            DefaultTableModel dtm = (DefaultTableModel) creditTable.getModel();
            dtm.setRowCount(0);
            int totalAmount = 0;
            int totalDiscount = 0;
            while (connect.resultSet.next()) {
                int billId = connect.resultSet.getInt("id");
                int amount = connect.resultSet.getInt("amount");
                totalAmount += amount;
                int discount = connect.resultSet.getInt("discount");
                totalDiscount += discount;
                int receviedAmount = connect.resultSet.getInt("recevied_amount");
                String paymentDate = connect.resultSet.getString("payment_date");
                String orderType = getOrderTypefromDB(connect.resultSet.getInt("order_id"));
                dtm.addRow(new Object[]{sno, billId, amount, discount, receviedAmount, paymentDate.split(" ")[0], orderType});
                sno++;
            }
            if (dtm.getRowCount() > 0) {
                dtm.addRow(new Object[]{"", "", "", "", "", "", ""});
                dtm.addRow(new Object[]{"", "", "", "", "", "Total :", totalAmount});
                dtm.addRow(new Object[]{"", "", "", "", "", "Discount :", totalDiscount});
                dtm.addRow(new Object[]{"", "", "", "", "", "Net Total :", totalAmount - totalDiscount});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void creditBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditBackButtonMouseClicked
        if (creditBackButton.isEnabled()) {
            creditTable.removeAll();
            creditTable.setModel(tempTableModel);
            setCreditReport();
            creditBackButton.setEnabled(false);
            creditGetButton.setEnabled(true);
        }
    }//GEN-LAST:event_creditBackButtonMouseClicked

    private void printButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printButtonMouseClicked
        JPanel panel = (JPanel) jTabbedPane1.getSelectedComponent();
        for (Component component : panel.getComponents()) {
            if (component instanceof JScrollPane jScrollPane) {
                JViewport viewport = jScrollPane.getViewport();
                JTable jTable = (JTable) viewport.getView();
                try {
                    boolean flag = jTable.print();
                    if (flag) {

                    }
                } catch (PrinterException pe) {

                }
            }
        }
//        printComponenet(panel);
    }//GEN-LAST:event_printButtonMouseClicked

    private void setDsrReport() {
        getDsrReportData("select * from payment where status = 'Completed' and payment_date >= CURRENT_DATE");
    }

    private void setSalesReport() {
        var time = LocalDate.now();
        var month = time.getMonthValue();
        var year = time.getYear();
        String startDate = String.valueOf(year) + "-" + String.valueOf(month) + "-01";
        getSalesReportData("select * from payment where status = 'Completed' and payment_date between '" + startDate + "' and '" + time + " 23:59:59'");
        comboTriggerFlag = true;
    }

    private void setCreditReport() {
        getCreditReportData("SELECT c.*,SUM(p.amount) AS amount FROM customer c JOIN "
                + "payment p ON p.`customer_id` = c.`id` WHERE p.`payment_type` = 'Credit' GROUP BY c.`id`");
    }

    private void getDsrReportData(String statement) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement(statement, false);
        try {
            int sno = 1;
            DefaultTableModel dtm = (DefaultTableModel) dsrTable.getModel();
            dtm.setRowCount(0);
            int totalAmount = 0;
            int totalDiscount = 0;
            while (connect.resultSet.next()) {
                int billId = connect.resultSet.getInt("id");
                int amount = connect.resultSet.getInt("amount");
                totalAmount += amount;
                int discount = connect.resultSet.getInt("discount");
                totalDiscount += discount;
                int receviedAmount = connect.resultSet.getInt("recevied_amount");
                String orderType = getOrderTypefromDB(connect.resultSet.getInt("order_id"));
                String paymentType = connect.resultSet.getString("payment_type");
                dtm.addRow(new Object[]{sno, billId, amount, discount, receviedAmount, orderType, paymentType});
                sno++;
            }
            if (dtm.getRowCount() > 0) {
                dtm.addRow(new Object[]{"", "", "", "", "", "", ""});
                dtm.addRow(new Object[]{"", "", "", "", "", "Total :", totalAmount});
                dtm.addRow(new Object[]{"", "", "", "", "", "Discount :", totalDiscount});
                dtm.addRow(new Object[]{"", "", "", "", "", "Net Total :", totalAmount - totalDiscount});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getSalesReportData(String statement) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement(statement, false);
        List<String> monthList = Arrays.asList("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
        var time = LocalDate.now();
        salesMonthComboBox1.removeAllItems();
        salesMonthComboBox2.removeAllItems();
        salesDayComboBox1.removeAllItems();
        salesDayComboBox2.removeAllItems();
        for (int i = 0; i < time.getMonthValue(); i++) {
            salesMonthComboBox1.addItem(monthList.get(i));
            salesMonthComboBox2.addItem(monthList.get(i));
        }
        salesMonthComboBox1.setSelectedIndex(time.getMonthValue() - 1);
        salesMonthComboBox2.setSelectedIndex(time.getMonthValue() - 1);

        for (int i = 0; i < time.getDayOfMonth(); i++) {
            salesDayComboBox1.addItem(String.valueOf(i + 1));
            salesDayComboBox2.addItem(String.valueOf(i + 1));
        }
        salesDayComboBox1.setSelectedIndex(0);
        salesDayComboBox2.setSelectedIndex(time.getDayOfMonth() - 1);

        try {
            int sno = 1;
            DefaultTableModel dtm = (DefaultTableModel) salesTable.getModel();
            dtm.setRowCount(0);
            int totalAmount = 0;
            int totalDiscount = 0;
            while (connect.resultSet.next()) {
                int billId = connect.resultSet.getInt("id");
                int amount = connect.resultSet.getInt("amount");
                totalAmount += amount;
                int discount = connect.resultSet.getInt("discount");
                totalDiscount += discount;
                int receviedAmount = connect.resultSet.getInt("recevied_amount");
                String paymentDate = connect.resultSet.getString("payment_date");
                String paymentType = connect.resultSet.getString("payment_type");
                dtm.addRow(new Object[]{sno, billId, amount, discount, receviedAmount, paymentDate.split(" ")[0], paymentType});
                sno++;
            }
            if (dtm.getRowCount() > 0) {
                dtm.addRow(new Object[]{"", "", "", "", "", "", ""});
                dtm.addRow(new Object[]{"", "", "", "", "", "Total :", totalAmount});
                dtm.addRow(new Object[]{"", "", "", "", "", "Discount :", totalDiscount});
                dtm.addRow(new Object[]{"", "", "", "", "", "Net Total :", totalAmount - totalDiscount});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getCreditReportData(String statement) {
        DBConnect connect = new DBConnect();
        connect.prepareStatement(statement, false);
        try {
            int sno = 1;
            DefaultTableModel dtm = (DefaultTableModel) creditTable.getModel();
            dtm.setRowCount(0);
            int totalAmount = 0;
            while (connect.resultSet.next()) {
                String firstName = connect.resultSet.getString("first_name");
                String lastName = connect.resultSet.getString("last_name");
                int amount = connect.resultSet.getInt("amount");
                totalAmount += amount;
                String mobile = connect.resultSet.getString("phone");
                dtm.addRow(new Object[]{sno, firstName, lastName, mobile, amount});
                sno++;
            }
            if (dtm.getRowCount() > 0) {
                dtm.addRow(new Object[]{"", "", "", "", ""});
                dtm.addRow(new Object[]{"", "", "", "Net Total :", totalAmount});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private int getOrderIdFromDB(int billId) {
        int orderId = 0;
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select order_id from `payment` where id=" + billId, false);
        try {
            if (connect.resultSet.next()) {
                orderId = connect.resultSet.getInt("order_id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return orderId;
    }

    private String getOrderTypefromDB(int orderId) {
        String text = "";
        DBConnect connect = new DBConnect();
        connect.prepareStatement("select type from `order` where id=" + orderId, false);
        try {
            if (connect.resultSet.next()) {
                text = connect.resultSet.getString("type");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return text;
    }

    private int getCustomerIdFromDB(String firstName, String lastName, String mobile) {
        DBConnect connect = new DBConnect();
        String statement = "select id from customer where first_name='" + firstName
                + "' and last_name='" + lastName + "' and phone='" + mobile + "'";
        connect.prepareStatement(statement, false);
        int id = 0;
        try {
            if (connect.resultSet.next()) {
                id = connect.resultSet.getInt("id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    public void printComponenet(Component component) {
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Component ");

        pj.setPrintable((Graphics pg, PageFormat pf, int pageNum) -> {
            if (pageNum > 0) {
                return Printable.NO_SUCH_PAGE;
            }

            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            component.paint(g2);
            return Printable.PAGE_EXISTS;
        });
        if (pj.printDialog() == false) {
            return;
        }

        try {
            pj.print();
        } catch (PrinterException ex) {
            // handle exception
        }
    }

    private DefaultTableModel tempTableModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditBackButton;
    private javax.swing.JComboBox<String> creditComboBox;
    private javax.swing.JButton creditGetButton;
    private javax.swing.JTable creditTable;
    private javax.swing.JPanel creditorPanel;
    private javax.swing.JComboBox<String> dsrComboBox1;
    private javax.swing.JComboBox<String> dsrComboBox2;
    private javax.swing.JButton dsrGetButton;
    private javax.swing.JPanel dsrPanel;
    private javax.swing.JTable dsrTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JComboBox<String> salesComboBox1;
    private javax.swing.JComboBox<String> salesComboBox2;
    private javax.swing.JComboBox<String> salesDayComboBox1;
    private javax.swing.JComboBox<String> salesDayComboBox2;
    private javax.swing.JButton salesGetButton;
    private javax.swing.JComboBox<String> salesMonthComboBox1;
    private javax.swing.JComboBox<String> salesMonthComboBox2;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JTable salesTable;
    private javax.swing.JComboBox<String> salesYearComboBox1;
    private javax.swing.JComboBox<String> salesYearComboBox2;
    // End of variables declaration//GEN-END:variables
}
