/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test1.luxcafe;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurva
 */
public class ReportDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form DsrReportForm
     */
    public ReportDetailsForm() {
        initComponents();
        checkOutButton.setVisible(false);
        setLocationRelativeTo(null);
    }

    public ReportDetailsForm(ReportPanel rp) {
        initComponents();
        reportPanel = rp;
        checkOutButton.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        billIdLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        orderTypeLabel = new javax.swing.JLabel();
        paymentTypeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        discountLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        receviedLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        customerLabel = new javax.swing.JLabel();
        waiterLabel = new javax.swing.JLabel();
        tableLabel = new javax.swing.JLabel();
        checkOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Order Details");

        billIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        billIdLabel.setText("Bill ID :");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("Date :");

        orderTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderTypeLabel.setText("Order Type :");

        paymentTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentTypeLabel.setText("Payment Type :");

        discountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discountLabel.setText("Discount :");

        amountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountLabel.setText("Total :");

        receviedLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        receviedLabel.setText("Recevied :");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "S.No.", "Item Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable.getColumnModel().getColumn(2).setMaxWidth(80);
            jTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        customerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerLabel.setText("Customer :");

        waiterLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waiterLabel.setText("Order By :");

        tableLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableLabel.setText("Table : ");

        checkOutButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkOutButton.setText("Check Out");
        checkOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(billIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(waiterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkOutButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tableLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(orderTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(receviedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(billIdLabel)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(waiterLabel)
                    .addComponent(paymentTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountLabel)
                    .addComponent(customerLabel)
                    .addComponent(orderTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receviedLabel)
                            .addComponent(tableLabel))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(checkOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutButtonMouseClicked
        JButton btn = (JButton) evt.getSource();
        if (btn.isEnabled()) {
            CheckoutForm checkoutForm = new CheckoutForm(btn, splitString(amountLabel.getText(), "Total : "),
                    Integer.parseInt(splitString(billIdLabel.getText(), "Bill ID : ")));
            checkoutForm.removeCreditPaymentType();
            checkoutForm.setVisible(true);
        }
    }//GEN-LAST:event_checkOutButtonMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!checkOutButton.isEnabled()) {
            reportPanel.reloadCreditReport();
        }
    }//GEN-LAST:event_formWindowClosed

    private String splitString(String string, String pattern) {
        return string.split(pattern)[1];
    }

    public void setData(String billId, int orderId, String amount, String discount, String recevied,
            String orderType, String paymentType, String date, String waiterName, String customerName, String tableName) {
        billIdLabel.setText(billIdLabel.getText() + " " + billId);
        amountLabel.setText(amountLabel.getText() + " " + amount);
        discountLabel.setText(discountLabel.getText() + " " + discount);
        receviedLabel.setText(receviedLabel.getText() + " " + recevied);
        orderTypeLabel.setText(orderTypeLabel.getText() + " " + orderType);
        paymentTypeLabel.setText(paymentTypeLabel.getText() + " " + paymentType);
        dateLabel.setText(dateLabel.getText() + " " + date);
        waiterLabel.setText("Order By : " + waiterName);
        customerLabel.setText("Customer : " + customerName);
        tableLabel.setText("Table : " + tableName);

        DBConnect connect = new DBConnect();
        connect.prepareStatement("SELECT od.quantity as quantity,od.price as price,m.name as `name` FROM "
                + "order_details od join menu m on m.id=od.`menu_id` where od.`order_id`=" + orderId, false);
        int i = 1;
        DefaultTableModel dtm = (DefaultTableModel) jTable.getModel();
        dtm.setRowCount(0);
        try {
            while (connect.resultSet.next()) {
                String name = connect.resultSet.getString("name");
                int quantity = connect.resultSet.getInt("quantity");
                int price = connect.resultSet.getInt("price");
                dtm.addRow(new Object[]{i, name, quantity, price});
            }

        } catch (SQLException ex) {
            Logger.getLogger(ReportDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void enableCheckoutButton() {
        checkOutButton.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportDetailsForm().setVisible(true);
            }
        });
    }

    ReportPanel reportPanel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel billIdLabel;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel orderTypeLabel;
    private javax.swing.JLabel paymentTypeLabel;
    private javax.swing.JLabel receviedLabel;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JLabel waiterLabel;
    // End of variables declaration//GEN-END:variables
}
